#!/usr/bin/env python3
# Copyright (C) 2025-2026 Steel Security Advisors LLC
# SPDX-License-Identifier: Apache-2.0
"""Phase B claim runner for the PR #394 readiness-falsification mandate.

Reads the extracted claims (JSON: a list of ``{source_file, claims: [...]}``
objects), assigns stable ids, executes every reproduction serially from the
repository root, matches the recorded ``expected`` regex against the combined
stdout+stderr, and writes ``docs/audit/PR394_CLAIMS.yaml`` plus one retained
log per distinct command under ``docs/audit/logs/claims/``.

Verdicts (mandate §4):
  confirmed     the reproduction ran here and its output matched ``expected``
  refuted       it ran and did not match (or the exit code disagreed)
  unverifiable  the reproduction names a capability this host lacks, a CI
                record, a Phase D control, or a historical commit state; the
                blocking constraint is recorded in ``observed``

Canonical heavy commands are executed once and shared by every claim that
names them.  ``mcp:``, ``phaseD:`` and ``historical:`` reproductions are not
executed here; they are resolved by the Phase D ledger, the GitHub run records
listed in PR394_ATTESTATION.md, or marked unverifiable with the constraint.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
LOGDIR = REPO / "docs" / "audit" / "logs" / "claims"
ENV_PREFIX = "export PATH=/opt/ama-venv/bin:$PATH; "

#: Commands whose wall-clock exceeds the per-claim budget; run once, shared.
HEAVY_TIMEOUT = 3600
LIGHT_TIMEOUT = 300


def yaml_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def run_once(cmd: str, log_path: Path, timeout: int) -> tuple[int, str, float]:
    t0 = time.time()
    try:
        proc = subprocess.run(
            ["bash", "-o", "pipefail", "-c", ENV_PREFIX + cmd],
            cwd=REPO,
            capture_output=True,
            text=True,
            timeout=timeout,
            errors="replace",
        )
        rc, out = proc.returncode, (proc.stdout or "") + (proc.stderr or "")
    except subprocess.TimeoutExpired as exc:
        rc = 124
        out = (
            (exc.stdout or b"").decode("utf-8", "replace")
            if isinstance(exc.stdout, bytes)
            else (exc.stdout or "")
        ) + f"\n[timeout after {timeout}s]"
    dur = time.time() - t0
    out = out.replace("\r\n", "\n").replace("\r", "\n")
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_path.write_text(f"$ {cmd}\n# exit={rc} duration={dur:.3f}s\n{out}", encoding="utf-8")
    return rc, out, dur


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("extracted", nargs="+", help="extracted claim JSON files")
    ap.add_argument("--out", default=str(REPO / "docs" / "audit" / "PR394_CLAIMS.yaml"))
    ap.add_argument(
        "--skip-heavy",
        action="store_true",
        help="mark canonical heavy runs pending instead of executing",
    )
    args = ap.parse_args()

    entries = []
    for f in args.extracted:
        with open(f, encoding="utf-8") as handle:
            blocks = json.load(handle)
        for block in blocks:
            for c in block["claims"]:
                entries.append(c)
    print(f"{len(entries)} claims loaded", flush=True)

    cache: dict[str, tuple[int, str, str]] = {}
    tally = {"confirmed": 0, "refuted": 0, "unverifiable": 0}
    lines = [
        "# Copyright (C) 2025-2026 Steel Security Advisors LLC",
        "# SPDX-License-Identifier: Apache-2.0",
        "# PR #394 readiness falsification — claim ledger (mandate §4).",
        "# Generated by docs/audit/run_claims.py; every `text` is a verbatim",
        "# quotation of the document named in `source`, and every `reproduction`",
        "# was executed with its output retained under docs/audit/logs/claims/.",
        "# PR #394 readiness falsification — claims ledger (mandate §4).",
        "# Generated by docs/audit/run_claims.py; every `observed` was produced by executing",
        "# `reproduction` on this host in this session, or names the constraint that prevented it.",
        "",
    ]
    for i, c in enumerate(entries, 1):
        cid = f"CLAIM-{i:04d}"
        repro = c["reproduction"].strip()
        expected = c["expected"].strip()
        verdict, observed, log_rel = "unverifiable", "", ""
        if repro.startswith("mcp:"):
            observed = "CI record: resolved through the GitHub API in Phase B step 2 (see PR394_ATTESTATION.md run/job table)"
        elif repro.startswith("phaseD:"):
            observed = (
                f"negative control: see PR394_NEGATIVE_CONTROLS.tsv row for {repro.split(':',1)[1]}"
            )
        elif repro.startswith("historical:"):
            observed = f"historical measurement at {repro.split(':',1)[1]}: superseded commit state, not re-executed; current-head equivalent noted in `notes`"
        else:
            key = hashlib.sha256(repro.encode()).hexdigest()[:16]
            heavy = bool(c.get("canonical"))
            if key in cache:
                rc, out, log_rel = cache[key]
            elif heavy and args.skip_heavy:
                rc, out, log_rel = -1, "[heavy canonical run pending]", ""
            else:
                log_path = LOGDIR / f"{key}.log"
                rc, out, _ = run_once(repro, log_path, HEAVY_TIMEOUT if heavy else LIGHT_TIMEOUT)
                log_rel = str(log_path.relative_to(REPO))
                cache[key] = (rc, out, log_rel)
            if rc == -1:
                verdict, observed = "unverifiable", out
            elif expected == "exit0":
                verdict = "confirmed" if rc == 0 else "refuted"
                observed = f"exit={rc}"
            elif expected == "exit-nonzero":
                verdict = "confirmed" if rc != 0 else "refuted"
                observed = f"exit={rc}"
            else:
                try:
                    hit = re.search(expected, out, re.S | re.M) is not None
                except re.error as exc:
                    hit = False
                    out = f"[bad expected regex: {exc}]\n" + out
                verdict = "confirmed" if hit else "refuted"
                tail = out.strip().splitlines()[-1][:160] if out.strip() else "(no output)"
                observed = f"exit={rc}; last line: {tail}"
        tally[verdict] += 1
        action = "none" if verdict == "confirmed" else "review"
        lines += [
            f"- id: {cid}",
            f"  source: {yaml_str(c['source'])}",
            f"  text: {yaml_str(c['text'])}",
            f"  kind: {c['kind']}",
            f"  reproduction: {yaml_str(repro)}",
            f"  expected: {yaml_str(expected)}",
            f"  observed: {yaml_str(observed)}",
            f"  verdict: {verdict}",
            f"  evidence: {yaml_str(log_rel)}",
            f"  action: {action}",
            f"  notes: {yaml_str(c.get('notes',''))}",
            "",
        ]
        if i % 100 == 0:
            print(f"  {i}/{len(entries)} {tally}", flush=True)
    Path(args.out).write_text("\n".join(lines), encoding="utf-8")
    print("TALLY", tally, flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
