# Copyright (C) 2025-2026 Steel Security Advisors LLC
# SPDX-License-Identifier: Apache-2.0
"""INVARIANT-36 — no third-party cryptographic implementation in the validation path.

``tools/check_corpus_originality.py`` enforces that AMA's correctness is measured
against published specifications and against its own reference encoder, never
against another cryptographic product. These tests pin both directions: the
repository passes today, and each class of violation is reproduced and required
to be caught.

The invariant exists because the repository failed it once. The key-format
conformance corpus carried twelve PEM files generated by OpenSSL, vendored as
the answer key for EC PKCS#8 and SPKI because RFC 5915 and RFC 5480 publish no
worked examples. Nothing linked or invoked OpenSSL at build or run time — but a
competing implementation's output was the thing AMA's correctness was measured
against, inside AMA's own repository, in a project whose stated position is that
it depends on no other cryptographic implementation.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOL_PATH = REPO_ROOT / "tools" / "check_corpus_originality.py"


def _load_tool() -> ModuleType:
    spec = importlib.util.spec_from_file_location("check_corpus_originality", TOOL_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def tool() -> ModuleType:
    return _load_tool()


# ---------------------------------------------------------------------------
# The anchor
# ---------------------------------------------------------------------------
def test_the_repository_holds_the_invariant(tool: ModuleType) -> None:
    assert tool.scan_for_binary_invocations() == []
    assert tool.scan_corpus_sources() == []
    assert tool.check_reference_encoder() == []


def test_the_cli_reports_success(tool: ModuleType) -> None:
    assert tool.main() == 0


def test_no_openssl_key_material_remains_anywhere_in_the_corpus() -> None:
    """The specific thing that was removed, asserted by name.

    Stated as its own test rather than folded into the generic scan, because
    this is the finding a reviewer will want to be able to point at.
    """
    corpus = REPO_ROOT / "tests" / "kat" / "keyformats"
    assert not (corpus / "openssl").exists(), (
        "the OpenSSL key corpus is back; RFC 9500 §2.3 publishes the EC keys it "
        "was standing in for"
    )
    for path in corpus.rglob("*"):
        assert path.suffix != ".pem", (
            f"{path} is a loose PEM file. Every vendored record lives in a JSON "
            "file that names the document it came from."
        )


def test_every_corpus_file_cites_an_rfc(tool: ModuleType) -> None:
    corpus = REPO_ROOT / "tests" / "kat" / "keyformats"
    seen = 0
    for path in sorted(corpus.glob("*.json")):
        source = json.loads(path.read_text())["source"]
        assert any(host in source["url"] for host in tool.STANDARDS_HOSTS), path.name
        assert source["title"] and source["revision"], path.name
        seen += 1
    assert seen >= 5, f"only {seen} corpus files found; the scan is not resolving"


# ---------------------------------------------------------------------------
# Failure directions
# ---------------------------------------------------------------------------
def test_a_subprocess_invocation_of_openssl_is_caught(tool: ModuleType, tmp_path: Path) -> None:
    """The exact shape the removed generator used."""
    (tmp_path / "tools").mkdir()
    (tmp_path / "tools" / "gen.py").write_text(
        "import subprocess\n"
        'subprocess.run(["openssl", "genpkey", "-algorithm", "EC"], check=True)\n'
    )
    problems = tool.scan_for_binary_invocations(tmp_path)
    assert any("openssl" in p and "gen.py" in p for p in problems), problems


@pytest.mark.parametrize("binary", ["gpg", "certtool", "keytool", "certutil"])
def test_other_cryptographic_binaries_are_caught(
    tool: ModuleType, tmp_path: Path, binary: str
) -> None:
    """Not an OpenSSL-shaped rule: any other implementation counts."""
    (tmp_path / "tests").mkdir()
    (tmp_path / "tests" / "t.py").write_text(
        f'import subprocess\nsubprocess.check_output("{binary} --version", shell=True)\n'
    )
    problems = tool.scan_for_binary_invocations(tmp_path)
    assert any(binary in p for p in problems), problems


def test_the_shipped_package_is_in_scope(tool: ModuleType, tmp_path: Path) -> None:
    """INVARIANT-1's strongest clause is about the shipped package, not the tests.

    ``legacy_compat.py`` shelled out to ``openssl ts`` to build and verify
    RFC 3161 timestamps — a competing implementation performing a cryptographic
    operation inside AMA at *runtime*, which is what INVARIANT-1 forbids in as
    many words. The scan originally covered ``tests/`` and ``tools/`` only and
    recorded that as an exception in its docstring. The exception is gone and
    so is the blind spot; this is what keeps it gone.
    """
    assert "ama_cryptography" in tool.SCAN_ROOTS, (
        "the shipped package must be scanned — it carries the strongest form of " "the rule"
    )
    (tmp_path / "ama_cryptography").mkdir()
    (tmp_path / "ama_cryptography" / "legacy_compat.py").write_text(
        "import subprocess\n"
        'subprocess.run(["openssl", "ts", "-query", "-data", "-"], capture_output=True)\n'
    )
    problems = tool.scan_for_binary_invocations(tmp_path)
    assert any("openssl" in p and "legacy_compat.py" in p for p in problems), problems


def test_the_real_package_invokes_no_cryptographic_binary(tool: ModuleType) -> None:
    """The live tree, not a fixture. This is the assertion that would have
    failed before the RFC 3161 work and must never fail again."""
    problems = [p for p in tool.scan_for_binary_invocations() if "ama_cryptography" in p]
    assert problems == [], problems


def test_a_mention_in_prose_is_not_a_finding(tool: ModuleType, tmp_path: Path) -> None:
    """This tree is full of "replaces OpenSSL X" comments — they are originality
    *claims*, and flagging them would make the gate un-satisfiable and push a
    maintainer to delete accurate documentation."""
    (tmp_path / "tools").mkdir()
    (tmp_path / "tools" / "note.py").write_text(
        '"""Replaces OpenSSL EVP_Digest; no openssl dependency."""\n'
        "# openssl is not used here\n"
        'OPENSSL_NOTE = "openssl"\n'
        "import subprocess\n"
        'subprocess.run(["python3", "-c", "pass"], check=True)\n'
    )
    assert tool.scan_for_binary_invocations(tmp_path) == []


def test_a_corpus_file_citing_a_non_standards_source_is_caught(
    tool: ModuleType, tmp_path: Path
) -> None:
    corpus = tmp_path / "keyformats"
    corpus.mkdir()
    (corpus / "vendor.json").write_text(
        json.dumps(
            {
                "source": {"url": "https://example.com/keys", "title": "t", "revision": "r"},
                "records": [],
            }
        )
    )
    problems = tool.scan_corpus_sources(corpus)
    assert any("not a standards-body archive" in p for p in problems), problems


def test_a_directory_of_key_files_in_the_corpus_is_caught(tool: ModuleType, tmp_path: Path) -> None:
    """How the third-party material was carried, so it is caught structurally
    and not only by the URL check."""
    corpus = tmp_path / "keyformats"
    (corpus / "somevendor").mkdir(parents=True)
    (corpus / "ok.json").write_text(
        json.dumps(
            {
                "source": {
                    "url": "https://www.rfc-editor.org/rfc/rfc9500.txt",
                    "title": "t",
                    "revision": "r",
                },
                "records": [],
            }
        )
    )
    # Deliberately *not* a literal PEM header: the check under test keys off
    # the directory, not the contents, and a real header here would be a finding
    # for tools/check_secrets.py (INVARIANT-23) in this very file.
    (corpus / "somevendor" / "P-256.key.pem").write_text("placeholder\n")
    problems = tool.scan_corpus_sources(corpus)
    assert any("unexpected directory" in p for p in problems), problems


def test_a_reference_encoder_that_imports_the_production_one_is_caught(
    tool: ModuleType, tmp_path: Path
) -> None:
    """The one-line change that would silently void every differential test."""
    path = tmp_path / "ref.py"
    path.write_text("from ama_cryptography._asn1 import der_sequence\n")
    problems = tool.check_reference_encoder(path)
    assert any("imports ama_cryptography" in p for p in problems), problems

    path.write_text("import ama_cryptography.key_formats as kf\n")
    assert tool.check_reference_encoder(path) != []


def test_a_missing_reference_encoder_is_a_failure(tool: ModuleType, tmp_path: Path) -> None:
    """Fail closed: the reference is what replaced the third-party corpus, so
    its absence must not read as everything being fine."""
    assert tool.check_reference_encoder(tmp_path / "gone.py") != []
