# Copyright (C) 2025-2026 Steel Security Advisors LLC
# SPDX-License-Identifier: Apache-2.0
"""Small-order Ed25519 public keys and R halves are rejected (INVARIANT-48).

``ama_ed25519_verify`` decides the **cofactorless** equation
``[S]B - R - [h]A = O`` — not the cofactored ``8([S]B - R - [h]A) = O`` that
ZIP-215 and libsodium's permissive mode decide — and until this invariant it
checked nothing about the *order* of ``A`` or ``R``. Set ``A`` to the identity
encoding and the ``[h]A`` term is the identity for every ``h``, so the equation
collapses to ``[S]B = R`` and the pair ``(R = [s]B, S = s)`` satisfies it for
**every message**. Measured against a pure-Python RFC 8032 reference at
``s in {1, 5, 12345}`` — all below ``L``, so the canonical-``S`` rule
(INVARIANT-26) does not block them — all three were ACCEPTED for all four
messages tried, through both the single and the batch entry point: 12 of 12
before the fix, 0 of 12 after. One 64-byte string, no secret, valid for
anything. It reached the package layer, where ``crypto_api`` embeds the public
key inside the package it verifies.

The finding is wider than the identity
--------------------------------------
The identity is the only key for which one signature works for every message,
but it is not the only forgeable one. For a small-order ``A`` of order ``n``,
``[h]A = [h mod n]A``, so an attacker holding no secret picks any ``S``, walks
``j`` over ``[0, n)``, sets ``R = [S]B - [j]A`` and keeps the first candidate
whose ``h = H(R || A || M)`` satisfies ``h == j (mod n)``. One in ``n``
candidates lands and ``n <= 8``. Constructed for all **eight** canonically
encoded small-order points: 8 of 8 accepted before the fix, 0 of 8 after.
Those eight are the load-bearing vectors here.

Why the obvious test would prove nothing
----------------------------------------
``tests/test_ed25519_canonical_y.py`` records what went wrong the last two
times this invariant family was tested, and the lesson applies verbatim: **a
rejection is only evidence when something that differs from it in exactly one
respect is accepted.** Putting a *genuine* signature to a small-order public
key and asserting ``False`` is vacuous — verify also returns ``False`` for the
wrong-key reason. Measured on this tree: 0 of 14 accepted both before and
after the fix. Those assertions live in :class:`TestSmokeCoverage` and are
named as smoke, not counted as coverage.

Every vector that *is* coverage satisfies the group equation under its
small-order input, so only the INVARIANT-48 predicate can reject it. The
library cannot produce such a signature — its signer has no way to emit one —
so they are fixed data, generated by a pure-Python RFC 8032 reference whose
own correctness is pinned by the §7.1 vectors in :class:`TestPositiveControl`.

Six encodings have no forgery vector
------------------------------------
Six of the fourteen never reach the group equation even without this fix:
``y = p`` and ``y = p+1`` under either sign fail INVARIANT-38's ``y < p`` rule,
and ``y = 1`` or ``y = p-1`` with the x-sign bit **set** fail its ``x = 0``
sign rule. A discriminating vector cannot be built for them because the
decoder refuses the encoding. ``tests/c/test_ed25519_small_order.c`` pins those
six directly against ``ama_ed25519_point_is_small_order()``, which this module
cannot reach — the predicate is a ``static inline`` in a private header with no
C-ABI symbol, so the Python side asserts behaviour and the C side asserts the
predicate.

Batch
-----
``ama_ed25519_batch_verify`` is an unconditional per-entry loop over
``ama_ed25519_verify``, so it inherits the rule by construction rather than by
a second copy of it. That is asserted rather than assumed: every vector below
is put to both entry points and the two verdicts compared.
"""

from __future__ import annotations

import pytest

from ama_cryptography.pqc_backends import (
    _native_lib,
    native_ed25519_batch_verify,
    native_ed25519_keypair,
    native_ed25519_sign,
    native_ed25519_verify,
)

pytestmark = pytest.mark.skipif(
    _native_lib is None,
    reason="Native C library not built — skipping small-order rejection tests",
)

P = 2**255 - 19

#: The message the per-key and R-half vectors were constructed against. It is
#: part of the vector: ``h = H(R || A || M)`` is what the construction solved
#: for, so changing this string invalidates every forgery vector below.
VECTOR_MSG = b"INVARIANT-48 discriminating vector"

#: Four messages for the universal forgery, which is message-independent by
#: construction — that independence is the whole point of the identity case.
UNIVERSAL_MSGS = (b"", b"abc", b"the quick brown fox", b"INVARIANT-48")

#: All fourteen 32-byte encodings of the eight points of the order-8 subgroup:
#: seven distinct ``y`` values, each under both settings of the x-sign bit.
SMALL_ORDER_ENCODINGS: tuple[tuple[str, bytes], ...] = (
    (
        "y=0 (order 4), sign 0",
        bytes.fromhex("0000000000000000000000000000000000000000000000000000000000000000"),
    ),
    (
        "y=0 (order 4), sign 1",
        bytes.fromhex("0000000000000000000000000000000000000000000000000000000000000080"),
    ),
    (
        "y=1 (identity), sign 0",
        bytes.fromhex("0100000000000000000000000000000000000000000000000000000000000000"),
    ),
    (
        "y=1 (identity), sign 1",
        bytes.fromhex("0100000000000000000000000000000000000000000000000000000000000080"),
    ),
    (
        "y=0x05fc..e826 (order 8), sign 0",
        bytes.fromhex("26e8958fc2b227b045c3f489f2ef98f0d5dfac05d3c63339b13802886d53fc05"),
    ),
    (
        "y=0x05fc..e826 (order 8), sign 1",
        bytes.fromhex("26e8958fc2b227b045c3f489f2ef98f0d5dfac05d3c63339b13802886d53fc85"),
    ),
    (
        "y=0x7a03..17c7 (order 8), sign 0",
        bytes.fromhex("c7176a703d4dd84fba3c0b760d10670f2a2053fa2c39ccc64ec7fd7792ac037a"),
    ),
    (
        "y=0x7a03..17c7 (order 8), sign 1",
        bytes.fromhex("c7176a703d4dd84fba3c0b760d10670f2a2053fa2c39ccc64ec7fd7792ac03fa"),
    ),
    (
        "y=p-1 (order 2), sign 0",
        bytes.fromhex("ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f"),
    ),
    (
        "y=p-1 (order 2), sign 1",
        bytes.fromhex("ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"),
    ),
    (
        "y=p -> 0 (non-canonical), sign 0",
        bytes.fromhex("edffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f"),
    ),
    (
        "y=p -> 0 (non-canonical), sign 1",
        bytes.fromhex("edffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"),
    ),
    (
        "y=p+1 -> 1 (non-canonical), sign 0",
        bytes.fromhex("eeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f"),
    ),
    (
        "y=p+1 -> 1 (non-canonical), sign 1",
        bytes.fromhex("eeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"),
    ),
)

UNIVERSAL_FORGERIES: tuple[tuple[int, bytes], ...] = (
    (
        1,
        bytes.fromhex(
            "5866666666666666666666666666666666666666666666666666666666666666"
            "0100000000000000000000000000000000000000000000000000000000000000"
        ),
    ),
    (
        5,
        bytes.fromhex(
            "edc876d6831fd2105d0b4389ca2e283166469289146e2ce06faefe98b22548df"
            "0500000000000000000000000000000000000000000000000000000000000000"
        ),
    ),
    (
        12345,
        bytes.fromhex(
            "ef4f62f8479733ad879cfaced3c89a9c39dd4fc795ef2efa1c3eafe4d729a081"
            "3930000000000000000000000000000000000000000000000000000000000000"
        ),
    ),
)

PER_KEY_FORGERIES: tuple[tuple[int, bytes, bytes], ...] = (
    (
        4,
        bytes.fromhex("0000000000000000000000000000000000000000000000000000000000000000"),
        bytes.fromhex(
            "3a25efff09b72b4f77b39dc058dae5ab3a4422d6703bae4e168620cf03a060af"
            "100f0e0d0c0b0a09080706050403020100000000000000000000000000000000"
        ),
    ),
    (
        4,
        bytes.fromhex("0000000000000000000000000000000000000000000000000000000000000080"),
        bytes.fromhex(
            "eeee6ef463eef473eec71f6af5818ca37f886541ead623996a81ae7d3cae25d4"
            "110f0e0d0c0b0a09080706050403020100000000000000000000000000000000"
        ),
    ),
    (
        1,
        bytes.fromhex("0100000000000000000000000000000000000000000000000000000000000000"),
        bytes.fromhex(
            "826fd18bec7a4360f953eb79aeb9bb3b471d11fdcf02ff7acd43d965f0f4c1e8"
            "100f0e0d0c0b0a09080706050403020100000000000000000000000000000000"
        ),
    ),
    (
        8,
        bytes.fromhex("26e8958fc2b227b045c3f489f2ef98f0d5dfac05d3c63339b13802886d53fc05"),
        bytes.fromhex(
            "c28ced103a25fce5aac852610d19a9ca3eaefe3037402b2d285832f5b43eadc1"
            "110f0e0d0c0b0a09080706050403020100000000000000000000000000000000"
        ),
    ),
    (
        8,
        bytes.fromhex("26e8958fc2b227b045c3f489f2ef98f0d5dfac05d3c63339b13802886d53fc85"),
        bytes.fromhex(
            "2b7312efc5da031a5537ad9ef2e65635c15101cfc8bfd4d2d7a7cd0a4bc1523e"
            "110f0e0d0c0b0a09080706050403020100000000000000000000000000000000"
        ),
    ),
    (
        8,
        bytes.fromhex("c7176a703d4dd84fba3c0b760d10670f2a2053fa2c39ccc64ec7fd7792ac037a"),
        bytes.fromhex(
            "8144f9da0d02f753f321b7412bf1a22a19b222889a17fab485cf3dcbda235c80"
            "120f0e0d0c0b0a09080706050403020100000000000000000000000000000000"
        ),
    ),
    (
        8,
        bytes.fromhex("c7176a703d4dd84fba3c0b760d10670f2a2053fa2c39ccc64ec7fd7792ac03fa"),
        bytes.fromhex(
            "e8f5bf9ee45e1727900f0c38ab4abd4a8d0404890fe22aba58d859f4398a02be"
            "100f0e0d0c0b0a09080706050403020100000000000000000000000000000000"
        ),
    ),
    (
        2,
        bytes.fromhex("ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f"),
        bytes.fromhex(
            "6b902e741385bc9f06ac1486514644c4b8e2ee0230fd008532bc269a0f0b3e17"
            "100f0e0d0c0b0a09080706050403020100000000000000000000000000000000"
        ),
    ),
)

R_IDENTITY_PUBLIC_KEY = bytes.fromhex(
    "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8"
)
R_IDENTITY_SIGNATURE = bytes.fromhex(
    "0100000000000000000000000000000000000000000000000000000000000000"
    "8d0a9d9d0c99c21b11bee6e51f1e59b1da00861f2d875de7b9243fe024b8f30b"
)

GENUINE_PUBLIC_KEY = bytes.fromhex(
    "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8"
)
GENUINE_SIGNATURE = bytes.fromhex(
    "b3a6c1cebb3c7686cb6b00e636486a99fcee79bb991a847004de852a19f35661"
    "a655bfb50a4fe688c48c1c1472636cbbca25ac3180164bef8b45b0abd7c6e00c"
)

#: RFC 8032 §7.1 TEST 1 / TEST 2 / TEST 3 as ``(message, signature, pk)``.
#: Regenerated from their §7.1 seeds by the same reference that built the
#: forgery vectors, which is how that reference was checked; TEST 1 is
#: byte-identical to the copy in ``tests/c/test_ed25519.c``.
RFC8032_VECTORS: tuple[tuple[bytes, bytes, bytes], ...] = (
    (
        b"",
        bytes.fromhex(
            "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e06522490155"
            "5fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b"
        ),
        bytes.fromhex("d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a"),
    ),
    (
        bytes.fromhex("72"),
        bytes.fromhex(
            "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da"
            "085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00"
        ),
        bytes.fromhex("3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c"),
    ),
    (
        bytes.fromhex("af82"),
        bytes.fromhex(
            "6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5ac3ac"
            "18ff9b538d16f290ae67f760984dc6594a7c15e9716ed28dc027beceea1ec40a"
        ),
        bytes.fromhex("fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025"),
    ),
)

#: The identity's canonical encoding, ``y = 1`` with the x-sign bit clear.
IDENTITY = SMALL_ORDER_ENCODINGS[2][1]


def verify_both(signature: bytes, message: bytes, public_key: bytes) -> bool:
    """Put one tuple to both entry points and require them to agree.

    Batch verification is a per-entry loop over ``ama_ed25519_verify``, so the
    two agreeing is a property of the code's shape rather than of a check
    duplicated in the batch path — which is exactly why it is asserted on
    every vector instead of argued once.
    """
    single = native_ed25519_verify(signature, message, public_key)
    batch = native_ed25519_batch_verify([(message, signature, public_key)])[0]
    assert single == batch, "batch verify disagreed with single verify on one 64-byte string"
    return single


class TestUniversalForgery:
    """``A = identity``: one signature, valid for every message.

    The audited finding. Each of these satisfies ``[S]B - R - [h]A = O`` for
    every message, so nothing but the small-order rule stands between them and
    acceptance.
    """

    @pytest.mark.parametrize("scalar,signature", UNIVERSAL_FORGERIES)
    @pytest.mark.parametrize("message", UNIVERSAL_MSGS)
    def test_forgery_is_rejected(self, scalar: int, signature: bytes, message: bytes) -> None:
        assert verify_both(signature, message, IDENTITY) is False

    @pytest.mark.parametrize("scalar,signature", UNIVERSAL_FORGERIES)
    def test_the_scalar_is_canonical(self, scalar: int, signature: bytes) -> None:
        """The rejection is not INVARIANT-26 doing the work by accident.

        ``S`` is 1, 5 or 12345 — far below ``L`` — so the canonical-``S``
        range check accepts every one of these signatures. If it did not, the
        test above would pass for the wrong reason.
        """
        L = 2**252 + 27742317777372353535851937790883648493
        s_half = int.from_bytes(signature[32:], "little")
        assert s_half == scalar
        assert s_half < L

    @pytest.mark.parametrize("scalar,signature", UNIVERSAL_FORGERIES)
    def test_the_r_half_is_not_itself_small_order(self, scalar: int, signature: bytes) -> None:
        """``R = [s]B`` is a prime-order point, so the ``R`` rule is not it either.

        Only the rule on ``A`` can reject these. Pinning that keeps the three
        input rules separable when one of them is next changed.
        """
        blocked = {enc[:31] + bytes([enc[31] & 0x7F]) for _, enc in SMALL_ORDER_ENCODINGS}
        r_half = signature[:32]
        assert r_half[:31] + bytes([r_half[31] & 0x7F]) not in blocked


class TestPerKeyForgery:
    """One signature per canonically encoded small-order ``A``.

    Built by the ``j``-search described in the module docstring: no secret is
    involved, only ``n <= 8`` hash evaluations. These satisfy the group
    equation under their key, which is what makes them evidence.
    """

    @pytest.mark.parametrize("order,public_key,signature", PER_KEY_FORGERIES)
    def test_forgery_is_rejected(self, order: int, public_key: bytes, signature: bytes) -> None:
        assert verify_both(signature, VECTOR_MSG, public_key) is False

    def test_all_eight_canonical_small_order_points_are_covered(self) -> None:
        """Every canonically encoded small-order point has a vector.

        Eight of the fourteen encodings are canonical; the other six are
        refused by INVARIANT-38 before the group equation is reached, so no
        such vector exists for them. If that ratio ever changes this assertion
        is where it surfaces.
        """
        canonical = {
            enc
            for _, enc in SMALL_ORDER_ENCODINGS
            if (int.from_bytes(enc, "little") & (2**255 - 1)) < P
            and not (enc[31] >> 7 and (int.from_bytes(enc, "little") & (2**255 - 1)) in (1, P - 1))
        }
        assert len(canonical) == 8
        assert {pk for _, pk, _ in PER_KEY_FORGERIES} == canonical


class TestSmallOrderR:
    """``R = identity`` with ``S = h*a mod L``, under a real public key.

    ``[S]B - R - [h]A`` is the identity exactly, so the group equation holds
    and INVARIANT-38's canonical-``R`` rule does not apply — this encoding *is*
    canonical, which is the difference from
    ``tests/c/test_ed25519_canonical_r.c``, whose vector uses the
    sign-bit-**set** spelling of the same point. Producing it needs the
    signer's own key, and that is the point: without this invariant a signer
    could mint a signature carrying no randomness at all and it would verify.

    No such vector exists for the other thirteen encodings: for a small-order
    ``T`` that is not the identity, ``[S]B = T + [h]A`` has no solution ``S``
    when ``A`` has prime order, because ``T`` is not in ``<B>``.
    """

    def test_identity_r_is_rejected(self) -> None:
        assert verify_both(R_IDENTITY_SIGNATURE, VECTOR_MSG, R_IDENTITY_PUBLIC_KEY) is False

    def test_the_public_key_is_a_real_one(self) -> None:
        """Not vacuous by way of the key: the same key verifies its own signature."""
        assert R_IDENTITY_PUBLIC_KEY == GENUINE_PUBLIC_KEY
        assert verify_both(GENUINE_SIGNATURE, VECTOR_MSG, GENUINE_PUBLIC_KEY) is True

    def test_the_r_half_is_the_canonical_identity_encoding(self) -> None:
        """Sign bit clear, so INVARIANT-38 is not what rejects it."""
        assert R_IDENTITY_SIGNATURE[:32] == IDENTITY
        assert R_IDENTITY_SIGNATURE[31] >> 7 == 0


class TestSmokeCoverage:
    """Rejected before the fix and after it — named so nobody counts it.

    Measured: 0 of 14 accepted both ways, because a signature made under a
    different key fails the group equation on its own. Kept for end-to-end
    coverage of all fourteen encodings and because a future refactor could
    make them discriminating.
    """

    @pytest.mark.parametrize("label,encoding", SMALL_ORDER_ENCODINGS)
    def test_smoke_small_order_public_key(self, label: str, encoding: bytes) -> None:
        assert verify_both(GENUINE_SIGNATURE, VECTOR_MSG, encoding) is False

    @pytest.mark.parametrize("label,encoding", SMALL_ORDER_ENCODINGS)
    def test_smoke_small_order_r_half(self, label: str, encoding: bytes) -> None:
        signature = encoding + GENUINE_SIGNATURE[32:]
        assert verify_both(signature, VECTOR_MSG, GENUINE_PUBLIC_KEY) is False


class TestTheFourteenEncodings:
    """The table itself: seven ``y`` values under both sign bits, and nothing else."""

    def test_there_are_exactly_fourteen(self) -> None:
        assert len(SMALL_ORDER_ENCODINGS) == 14
        assert len({enc for _, enc in SMALL_ORDER_ENCODINGS}) == 14

    def test_they_are_seven_y_values_under_both_sign_bits(self) -> None:
        ys = {int.from_bytes(enc, "little") & (2**255 - 1) for _, enc in SMALL_ORDER_ENCODINGS}
        y8a = 0x05FC536D880238B13933C6D305ACDFD5F098EFF289F4C345B027B2C28F95E826
        y8b = 0x7A03AC9277FDC74EC6CC392CFA53202A0F67100D760B3CBA4FD84D3D706A17C7
        assert ys == {0, 1, y8a, y8b, P - 1, P, P + 1}

    def test_only_p_and_p_plus_one_come_from_the_non_canonical_band(self) -> None:
        """``[p, 2^255)`` holds nineteen values; exactly two reduce into the set.

        This is what makes the fourteen complete rather than a sample. The
        sweep is cheap enough to run rather than cite.
        """
        y8a = 0x05FC536D880238B13933C6D305ACDFD5F098EFF289F4C345B027B2C28F95E826
        y8b = 0x7A03AC9277FDC74EC6CC392CFA53202A0F67100D760B3CBA4FD84D3D706A17C7
        small = {0, 1, y8a, y8b, P - 1}
        assert {y for y in range(P, 2**255) if y % P in small} == {P, P + 1}


class TestPositiveControl:
    """What must still be accepted. Without this the module passes on a verifier
    that returns ``False`` unconditionally."""

    def test_the_reference_generated_signature_verifies(self) -> None:
        assert verify_both(GENUINE_SIGNATURE, VECTOR_MSG, GENUINE_PUBLIC_KEY) is True

    @pytest.mark.parametrize("message,signature,public_key", RFC8032_VECTORS)
    def test_rfc8032_section_7_1(self, message: bytes, signature: bytes, public_key: bytes) -> None:
        assert verify_both(signature, message, public_key) is True

    def test_freshly_generated_signatures_verify(self) -> None:
        """Fixed vectors cannot show that the sign path is unaffected; this can."""
        for _ in range(8):
            public_key, secret_key = native_ed25519_keypair()
            signature = native_ed25519_sign(VECTOR_MSG, secret_key)
            assert verify_both(signature, VECTOR_MSG, public_key) is True
            assert public_key not in {enc for _, enc in SMALL_ORDER_ENCODINGS}


class TestMixedBatch:
    """Batch cannot be answering "reject everything"."""

    def test_one_genuine_entry_survives_the_company_it_keeps(self) -> None:
        entries = [(VECTOR_MSG, GENUINE_SIGNATURE, GENUINE_PUBLIC_KEY)]
        entries += [(VECTOR_MSG, sig, IDENTITY) for _, sig in UNIVERSAL_FORGERIES]
        entries += [(VECTOR_MSG, sig, pk) for _, pk, sig in PER_KEY_FORGERIES]
        entries.append((VECTOR_MSG, R_IDENTITY_SIGNATURE, R_IDENTITY_PUBLIC_KEY))

        results = native_ed25519_batch_verify(entries)
        assert results[0] is True
        assert results[1:] == [False] * (len(entries) - 1)

    def test_batch_matches_single_entry_for_entry(self) -> None:
        """The inheritance claim, stated over the whole corpus at once."""
        entries = [(VECTOR_MSG, GENUINE_SIGNATURE, GENUINE_PUBLIC_KEY)]
        entries += [
            (msg, sig, IDENTITY) for _, sig in UNIVERSAL_FORGERIES for msg in UNIVERSAL_MSGS
        ]
        entries += [(VECTOR_MSG, sig, pk) for _, pk, sig in PER_KEY_FORGERIES]
        entries += [(VECTOR_MSG, GENUINE_SIGNATURE, enc) for _, enc in SMALL_ORDER_ENCODINGS]
        entries += [
            (VECTOR_MSG, enc + GENUINE_SIGNATURE[32:], GENUINE_PUBLIC_KEY)
            for _, enc in SMALL_ORDER_ENCODINGS
        ]
        entries += [(msg, sig, pk) for msg, sig, pk in RFC8032_VECTORS]

        batched = native_ed25519_batch_verify(entries)
        singly = [native_ed25519_verify(sig, msg, pk) for msg, sig, pk in entries]
        assert batched == singly
