/* Copyright (C) 2025-2026 Steel Security Advisors LLC */
/* SPDX-License-Identifier: Apache-2.0 */
/**
 * @file test_lms.c
 * @brief RFC 8554 HSS/LMS verification — Appendix F KAT plus rejection sweep
 *
 * The vectors are read from `tests/kat/keyformats/rfc8554_hss_lms.json`, the
 * same corpus `tests/test_rfc8554_vectors.py` structurally validates and the
 * corpus-provenance gate checks against rfc-editor.org.  They are *not*
 * transcribed into this file: a second copy of a vector is a second thing to
 * keep true, and the failure mode of a drifted copy is a test that passes
 * against the wrong answer.
 *
 * What is checked, and why each layer exists
 * ------------------------------------------
 *  1. Both published HSS test cases verify.  Case 1 is L=2 over
 *     LMS_SHA256_M32_H5 + LMOTS_SHA256_N32_W8; case 2 is L=2 over
 *     LMS_SHA256_M32_H10 + LMOTS_SHA256_N32_W4.  Between them they exercise
 *     two tree heights and two Winternitz widths, which is two distinct
 *     `coef`/`Cksm` paths and two distinct chain lengths.
 *  2. Every single-byte position class is corrupted and must be rejected:
 *     message, public key, each level's signature, the embedded intermediate
 *     public key, and the Merkle path.  A verifier that ignores a field is
 *     indistinguishable from one that checks it until you flip that field.
 *  3. The inner LMS signature is split out with `ama_lms_signature_length`
 *     and verified on its own against the intermediate public key the HSS
 *     signature carries — so the length walker and the single-tree verifier
 *     each get an independent, positive exercise rather than only being
 *     reachable through the HSS path.
 *  4. Structural rejection: truncation at every boundary, trailing data,
 *     mismatched Nspk, unknown typecodes, an out-of-range leaf index `q`,
 *     and an over-deep L.  A parser reached by an attacker-supplied file has
 *     to be shown refusing, not merely shown accepting.
 */

#include "../../include/ama_cryptography.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int g_failures = 0;
static int g_checks = 0;

#define CHECK(cond, ...)                                                                           \
    do {                                                                                           \
        g_checks++;                                                                                \
        if (!(cond)) {                                                                             \
            g_failures++;                                                                          \
            printf("  FAIL %s:%d: ", __FILE__, __LINE__);                                          \
            printf(__VA_ARGS__);                                                                   \
            printf("\n");                                                                          \
        }                                                                                          \
    } while (0)

/* ============================================================================
 * Corpus loading
 *
 * The corpus is machine-generated by tools/build_keyformat_corpus.py with a
 * fixed key order (section, case, kind, hex, bytes), so a field scan is
 * sufficient and needs no JSON parser in the test binary.  The scan is strict:
 * a record it cannot locate is a failure, never a silently skipped case.
 * ============================================================================ */

typedef struct {
    uint8_t *data;
    size_t len;
} blob;

/* Bounds on what this harness will read and decode.
 *
 * Every length below originates in a *file*, and a length taken from a file is
 * an unbounded length until something bounds it — even in a test, where the
 * file is one this repository ships. The corpus is ~15 KB and its largest
 * record is a 3,860-octet signature, so these are two orders of magnitude of
 * headroom and still a bound. Without them the harness is one truncated write
 * away from a multi-gigabyte allocation, and it would be reporting that as a
 * malloc failure rather than as the corrupt corpus it is. */
#define CORPUS_MAX_BYTES (1u * 1024u * 1024u)
#define RECORD_MAX_BYTES (64u * 1024u)

static char *g_corpus;

static char *read_whole_file(const char *path) {
    FILE *f = fopen(path, "rb");
    long size;
    char *buf;

    if (f == NULL)
        return NULL;
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        return NULL;
    }
    size = ftell(f);
    if (size <= 0 || (unsigned long)size > CORPUS_MAX_BYTES) {
        fclose(f);
        return NULL;
    }
    rewind(f);
    buf = (char *)malloc((size_t)size + 1u);
    if (buf == NULL) {
        fclose(f);
        return NULL;
    }
    if (fread(buf, 1, (size_t)size, f) != (size_t)size) {
        free(buf);
        fclose(f);
        return NULL;
    }
    buf[size] = '\0';
    fclose(f);
    return buf;
}

/** Locate the corpus whether ctest runs from the build tree or the source root. */
static char *load_corpus(void) {
    static const char *candidates[] = {
        "tests/kat/keyformats/rfc8554_hss_lms.json",
        "../tests/kat/keyformats/rfc8554_hss_lms.json",
        "../../tests/kat/keyformats/rfc8554_hss_lms.json",
        "../../../tests/kat/keyformats/rfc8554_hss_lms.json",
    };
    size_t i;
    for (i = 0; i < sizeof(candidates) / sizeof(candidates[0]); i++) {
        char *buf = read_whole_file(candidates[i]);
        if (buf != NULL)
            return buf;
    }
    return NULL;
}

static int hex_nibble(char c) {
    if (c >= '0' && c <= '9')
        return c - '0';
    if (c >= 'a' && c <= 'f')
        return c - 'a' + 10;
    if (c >= 'A' && c <= 'F')
        return c - 'A' + 10;
    return -1;
}

/**
 * Fetch the `hex` value of the record whose `case` is `want_case` and whose
 * `kind` is `want_kind`.  Returns a heap blob the caller frees, or {NULL, 0}.
 */
static blob corpus_record(int want_case, const char *want_kind) {
    blob out = {NULL, 0};
    char case_needle[64];
    char kind_needle[64];
    const char *cursor;

    snprintf(case_needle, sizeof(case_needle), "\"case\": %d,", want_case);
    snprintf(kind_needle, sizeof(kind_needle), "\"kind\": \"%s\",", want_kind);

    cursor = g_corpus;
    while ((cursor = strstr(cursor, case_needle)) != NULL) {
        const char *kind = strstr(cursor, "\"kind\":");
        const char *next_case;
        const char *hex;
        const char *end;
        size_t nhex;
        size_t i;

        cursor += strlen(case_needle);
        if (kind == NULL)
            break;
        /* The kind must belong to *this* record, i.e. appear before the next
         * record's "case" key. */
        next_case = strstr(cursor, "\"case\":");
        if (next_case != NULL && kind > next_case)
            continue;
        if (strncmp(kind, kind_needle, strlen(kind_needle)) != 0)
            continue;

        hex = strstr(kind, "\"hex\": \"");
        if (hex == NULL)
            break;
        hex += strlen("\"hex\": \"");
        end = strchr(hex, '"');
        if (end == NULL)
            break;
        nhex = (size_t)(end - hex);
        if (nhex % 2u != 0u || nhex / 2u > RECORD_MAX_BYTES)
            break;
        out.len = nhex / 2u;
        out.data = (uint8_t *)malloc(out.len == 0 ? 1u : out.len);
        if (out.data == NULL) {
            out.len = 0;
            break;
        }
        for (i = 0; i < out.len; i++) {
            int hi = hex_nibble(hex[2 * i]);
            int lo = hex_nibble(hex[2 * i + 1]);
            if (hi < 0 || lo < 0) {
                free(out.data);
                out.data = NULL;
                out.len = 0;
                return out;
            }
            out.data[i] = (uint8_t)((hi << 4) | lo);
        }
        return out;
    }
    return out;
}

/* ============================================================================
 * 1. The published answer key
 * ============================================================================ */

typedef struct {
    blob msg;
    blob pub;
    blob sig;
} testcase;

static int load_case(int n, testcase *tc) {
    tc->msg = corpus_record(n, "message");
    tc->pub = corpus_record(n, "public_key");
    tc->sig = corpus_record(n, "signature");
    return tc->msg.data != NULL && tc->pub.data != NULL && tc->sig.data != NULL;
}

static void free_case(testcase *tc) {
    free(tc->msg.data);
    free(tc->pub.data);
    free(tc->sig.data);
    memset(tc, 0, sizeof(*tc));
}

static void test_appendix_f_verifies(const testcase *tc, int n) {
    ama_error_t rc =
        ama_hss_verify(tc->msg.data, tc->msg.len, tc->sig.data, tc->sig.len, tc->pub.data,
                       tc->pub.len);
    CHECK(rc == AMA_SUCCESS, "Appendix F test case %d did not verify (rc=%d)", n, (int)rc);
}

static void test_public_key_shape(const testcase *tc, int n, uint32_t expect_lms,
                                  uint32_t expect_ots, uint32_t expect_h, uint32_t expect_w) {
    uint32_t levels = 0, lms_type = 0, ots_type = 0, h = 0, w = 0;
    ama_error_t rc;

    CHECK(tc->pub.len == AMA_HSS_PUBKEY_LEN, "case %d HSS public key is %zu bytes, expected %d", n,
          tc->pub.len, AMA_HSS_PUBKEY_LEN);

    rc = ama_hss_pubkey_levels(tc->pub.data, tc->pub.len, &levels);
    CHECK(rc == AMA_SUCCESS && levels == 2u, "case %d levels: rc=%d L=%u (expected 2)", n, (int)rc,
          levels);

    rc = ama_lms_pubkey_params(tc->pub.data + 4, tc->pub.len - 4, &lms_type, &ots_type, &h, &w);
    CHECK(rc == AMA_SUCCESS, "case %d lms_pubkey_params rc=%d", n, (int)rc);
    CHECK(lms_type == expect_lms, "case %d lms type %u, expected %u", n, lms_type, expect_lms);
    CHECK(ots_type == expect_ots, "case %d ots type %u, expected %u", n, ots_type, expect_ots);
    CHECK(h == expect_h, "case %d h=%u, expected %u", n, h, expect_h);
    CHECK(w == expect_w, "case %d w=%u, expected %u", n, w, expect_w);
}

/* ============================================================================
 * 2. Corruption sweep — every field must be load-bearing
 * ============================================================================ */

static int verifies(const testcase *tc, const uint8_t *msg, size_t msg_len, const uint8_t *sig,
                    size_t sig_len, const uint8_t *pub, size_t pub_len) {
    (void)tc;
    return ama_hss_verify(msg, msg_len, sig, sig_len, pub, pub_len) == AMA_SUCCESS;
}

static void test_every_signature_octet_is_load_bearing(const testcase *tc, int n) {
    /* Corrupting all 2644/3860 octets one at a time would be 2644 full
     * verifications; sample a stride that still lands in every structural
     * region (Nspk, level-0 OTS signature, level-0 path, embedded public key,
     * level-1 OTS signature, level-1 path) plus both endpoints. */
    size_t stride = tc->sig.len / 64u;
    size_t i;
    uint8_t *mutated = (uint8_t *)malloc(tc->sig.len);
    int rejected_all = 1;

    if (mutated == NULL) {
        CHECK(0, "out of memory");
        return;
    }
    if (stride == 0)
        stride = 1;

    for (i = 0; i < tc->sig.len; i += stride) {
        memcpy(mutated, tc->sig.data, tc->sig.len);
        mutated[i] ^= 0x01u;
        if (verifies(tc, tc->msg.data, tc->msg.len, mutated, tc->sig.len, tc->pub.data,
                     tc->pub.len)) {
            rejected_all = 0;
            printf("  case %d: flipping signature octet %zu was NOT detected\n", n, i);
        }
    }
    /* The last octet specifically — an off-by-one in the path walk would
     * leave it unread. */
    memcpy(mutated, tc->sig.data, tc->sig.len);
    mutated[tc->sig.len - 1u] ^= 0x80u;
    if (verifies(tc, tc->msg.data, tc->msg.len, mutated, tc->sig.len, tc->pub.data, tc->pub.len)) {
        rejected_all = 0;
        printf("  case %d: flipping the final signature octet was NOT detected\n", n);
    }
    CHECK(rejected_all, "case %d: at least one signature octet was ignored", n);
    free(mutated);
}

static void test_message_and_public_key_are_load_bearing(const testcase *tc, int n) {
    uint8_t *m = (uint8_t *)malloc(tc->msg.len);
    uint8_t *p = (uint8_t *)malloc(tc->pub.len);
    size_t i;
    int ok = 1;

    if (m == NULL || p == NULL) {
        CHECK(0, "out of memory");
        free(m);
        free(p);
        return;
    }

    memcpy(m, tc->msg.data, tc->msg.len);
    m[0] ^= 0x01u;
    ok &= !verifies(tc, m, tc->msg.len, tc->sig.data, tc->sig.len, tc->pub.data, tc->pub.len);
    memcpy(m, tc->msg.data, tc->msg.len);
    m[tc->msg.len - 1u] ^= 0x01u;
    ok &= !verifies(tc, m, tc->msg.len, tc->sig.data, tc->sig.len, tc->pub.data, tc->pub.len);
    /* Truncating the message must not verify either — the length is inside
     * the hashed preimage, but only because it is fed in as data. */
    ok &= !verifies(tc, tc->msg.data, tc->msg.len - 1u, tc->sig.data, tc->sig.len, tc->pub.data,
                    tc->pub.len);
    CHECK(ok, "case %d: a message mutation was not detected", n);

    /* Every octet of the 32-byte root must matter. */
    ok = 1;
    for (i = 0; i < 32u; i++) {
        memcpy(p, tc->pub.data, tc->pub.len);
        p[tc->pub.len - 32u + i] ^= 0x01u;
        ok &= !verifies(tc, tc->msg.data, tc->msg.len, tc->sig.data, tc->sig.len, p, tc->pub.len);
    }
    /* And so must the 16-byte identifier I. */
    for (i = 0; i < 16u; i++) {
        memcpy(p, tc->pub.data, tc->pub.len);
        p[12u + i] ^= 0x01u;
        ok &= !verifies(tc, tc->msg.data, tc->msg.len, tc->sig.data, tc->sig.len, p, tc->pub.len);
    }
    CHECK(ok, "case %d: a public-key mutation was not detected", n);

    free(m);
    free(p);
}

/* ============================================================================
 * 3. The single-tree verifier and the length walker, exercised on their own
 * ============================================================================ */

static void test_inner_lms_level_verifies_standalone(const testcase *tc, int n) {
    /* HSS signature layout for L=2: u32(Nspk) || sig[0] || pub[1] || sig[1].
     * Split it with the public length walker and check each half. */
    const uint8_t *body = tc->sig.data + 4;
    size_t remaining = tc->sig.len - 4u;
    size_t sig0 = ama_lms_signature_length(body, remaining);
    size_t pub1_len = AMA_LMS_PUBKEY_LEN;
    const uint8_t *pub1;
    size_t sig1;
    ama_error_t rc;

    CHECK(sig0 > 0 && sig0 < remaining, "case %d: level-0 signature length walker returned %zu", n,
          sig0);
    if (sig0 == 0 || sig0 >= remaining)
        return;

    pub1 = body + sig0;
    CHECK(remaining - sig0 > pub1_len, "case %d: no room for the embedded public key", n);
    if (remaining - sig0 <= pub1_len)
        return;

    /* Level 0 signs the level-1 public key. */
    rc = ama_lms_verify(pub1, pub1_len, body, sig0, tc->pub.data + 4, tc->pub.len - 4);
    CHECK(rc == AMA_SUCCESS, "case %d: level-0 LMS signature over pub[1] failed (rc=%d)", n,
          (int)rc);

    /* Level 1 signs the message. */
    sig1 = remaining - sig0 - pub1_len;
    CHECK(ama_lms_signature_length(pub1 + pub1_len, sig1) == sig1,
          "case %d: level-1 signature length walker disagrees with the remainder", n);
    rc = ama_lms_verify(tc->msg.data, tc->msg.len, pub1 + pub1_len, sig1, pub1, pub1_len);
    CHECK(rc == AMA_SUCCESS, "case %d: level-1 LMS signature over the message failed (rc=%d)", n,
          (int)rc);

    /* Cross-level substitution must fail: pub[1] does not verify sig[0]'s
     * message under its own key, and the outer root does not verify sig[1]. */
    CHECK(ama_lms_verify(tc->msg.data, tc->msg.len, pub1 + pub1_len, sig1, tc->pub.data + 4,
                         tc->pub.len - 4) != AMA_SUCCESS,
          "case %d: level-1 signature verified under the level-0 key", n);
}

/* ============================================================================
 * 4. Structural rejection
 * ============================================================================ */

static void test_structural_rejection(const testcase *tc, int n) {
    uint8_t *sig;
    uint8_t *pub;
    size_t i;
    int ok;

    sig = (uint8_t *)malloc(tc->sig.len + 1u);
    pub = (uint8_t *)malloc(tc->pub.len);
    if (sig == NULL || pub == NULL) {
        CHECK(0, "out of memory");
        free(sig);
        free(pub);
        return;
    }

    /* Truncation at every 64-byte boundary, and at every boundary in the
     * first 64 bytes where the headers live. */
    ok = 1;
    for (i = 0; i < tc->sig.len; i += (i < 64u ? 1u : 61u)) {
        if (verifies(tc, tc->msg.data, tc->msg.len, tc->sig.data, i, tc->pub.data, tc->pub.len)) {
            ok = 0;
            printf("  case %d: a signature truncated to %zu bytes verified\n", n, i);
        }
    }
    CHECK(ok, "case %d: a truncated signature verified", n);

    /* Trailing data.  Two byte strings that both verify for one message is
     * signature malleability, which is exactly what the exact-length rule in
     * Algorithm 6a step 2i exists to prevent. */
    memcpy(sig, tc->sig.data, tc->sig.len);
    sig[tc->sig.len] = 0x00u;
    CHECK(!verifies(tc, tc->msg.data, tc->msg.len, sig, tc->sig.len + 1u, tc->pub.data,
                    tc->pub.len),
          "case %d: a signature with a trailing octet verified", n);

    /* Nspk that disagrees with the public key's L. */
    memcpy(sig, tc->sig.data, tc->sig.len);
    sig[3] = 0x00u; /* Nspk = 0, but L = 2 */
    CHECK(!verifies(tc, tc->msg.data, tc->msg.len, sig, tc->sig.len, tc->pub.data, tc->pub.len),
          "case %d: Nspk=0 accepted against L=2", n);
    memcpy(sig, tc->sig.data, tc->sig.len);
    sig[3] = 0x07u;
    CHECK(!verifies(tc, tc->msg.data, tc->msg.len, sig, tc->sig.len, tc->pub.data, tc->pub.len),
          "case %d: Nspk=7 accepted against L=2", n);
    memcpy(sig, tc->sig.data, tc->sig.len);
    sig[0] = 0xFFu;
    sig[1] = 0xFFu;
    sig[2] = 0xFFu;
    sig[3] = 0xFFu;
    CHECK(!verifies(tc, tc->msg.data, tc->msg.len, sig, tc->sig.len, tc->pub.data, tc->pub.len),
          "case %d: Nspk=2^32-1 accepted (integer wrap in the level check)", n);

    /* Unknown typecodes anywhere must be refused, never resolved onto a
     * neighbour (INVARIANT-35). */
    memcpy(pub, tc->pub.data, tc->pub.len);
    pub[3] = 0x00u; /* L = 0 */
    CHECK(ama_hss_verify(tc->msg.data, tc->msg.len, tc->sig.data, tc->sig.len, pub, tc->pub.len) ==
              AMA_ERROR_INVALID_PARAM,
          "case %d: L=0 public key was not rejected as malformed", n);
    memcpy(pub, tc->pub.data, tc->pub.len);
    pub[3] = (uint8_t)(AMA_HSS_MAX_LEVELS + 1);
    CHECK(ama_hss_verify(tc->msg.data, tc->msg.len, tc->sig.data, tc->sig.len, pub, tc->pub.len) ==
              AMA_ERROR_INVALID_PARAM,
          "case %d: L above AMA_HSS_MAX_LEVELS was not rejected", n);
    memcpy(pub, tc->pub.data, tc->pub.len);
    pub[7] = 0x63u; /* LMS typecode 99 */
    CHECK(ama_hss_verify(tc->msg.data, tc->msg.len, tc->sig.data, tc->sig.len, pub, tc->pub.len) ==
              AMA_ERROR_INVALID_PARAM,
          "case %d: unknown LMS typecode was not rejected", n);
    memcpy(pub, tc->pub.data, tc->pub.len);
    pub[11] = 0x63u; /* LM-OTS typecode 99 */
    CHECK(ama_hss_verify(tc->msg.data, tc->msg.len, tc->sig.data, tc->sig.len, pub, tc->pub.len) ==
              AMA_ERROR_INVALID_PARAM,
          "case %d: unknown LM-OTS typecode was not rejected", n);

    /* A public key of the wrong length. */
    CHECK(ama_hss_verify(tc->msg.data, tc->msg.len, tc->sig.data, tc->sig.len, tc->pub.data,
                         tc->pub.len - 1u) == AMA_ERROR_INVALID_PARAM,
          "case %d: a short public key was not rejected", n);
    CHECK(ama_hss_verify(tc->msg.data, tc->msg.len, tc->sig.data, tc->sig.len, tc->pub.data, 3u) ==
              AMA_ERROR_INVALID_PARAM,
          "case %d: a 3-byte public key was not rejected", n);

    /* An out-of-range leaf index.  Case 1's level-0 tree is h=5, so q must be
     * below 32; q lives in the first four octets of sig[0], at offset 4. */
    memcpy(sig, tc->sig.data, tc->sig.len);
    sig[4] = 0xFFu;
    sig[5] = 0xFFu;
    sig[6] = 0xFFu;
    sig[7] = 0xFFu;
    CHECK(!verifies(tc, tc->msg.data, tc->msg.len, sig, tc->sig.len, tc->pub.data, tc->pub.len),
          "case %d: q = 2^32-1 was accepted", n);

    /* NULL handling. */
    CHECK(ama_hss_verify(NULL, 1u, tc->sig.data, tc->sig.len, tc->pub.data, tc->pub.len) ==
              AMA_ERROR_INVALID_PARAM,
          "NULL message with a non-zero length was not rejected");
    CHECK(ama_hss_verify(tc->msg.data, tc->msg.len, NULL, tc->sig.len, tc->pub.data, tc->pub.len) ==
              AMA_ERROR_INVALID_PARAM,
          "NULL signature was not rejected");
    CHECK(ama_hss_verify(tc->msg.data, tc->msg.len, tc->sig.data, tc->sig.len, NULL,
                         tc->pub.len) == AMA_ERROR_INVALID_PARAM,
          "NULL public key was not rejected");
    CHECK(ama_lms_verify(NULL, 1u, tc->sig.data, tc->sig.len, tc->pub.data + 4, tc->pub.len - 4) ==
              AMA_ERROR_INVALID_PARAM,
          "ama_lms_verify: NULL message with a non-zero length was not rejected");
    CHECK(ama_lms_signature_length(NULL, 100u) == 0, "length walker accepted NULL");
    CHECK(ama_lms_signature_length(tc->sig.data, 3u) == 0, "length walker accepted a 3-byte buffer");

    free(sig);
    free(pub);
}

static void test_signing_is_reported_absent(void) {
    CHECK(ama_lms_signing_available() == 0,
          "ama_lms_signing_available() must report 0 until a fail-closed durable "
          "state manager exists (RFC 8554 §5.4.1)");
}

int main(void) {
    testcase tc1;
    testcase tc2;

    printf("=== HSS/LMS verification (RFC 8554) test suite ===\n\n");

    g_corpus = load_corpus();
    if (g_corpus == NULL) {
        printf("  FAIL cannot open tests/kat/keyformats/rfc8554_hss_lms.json\n");
        printf("\n0 checks, 1 failures\n");
        return 1;
    }

    if (!load_case(1, &tc1) || !load_case(2, &tc2)) {
        printf("  FAIL corpus is missing a record for one of the two test cases\n");
        printf("\n0 checks, 1 failures\n");
        return 1;
    }

    /* Case 1: L=2, LMS_SHA256_M32_H5 (5) + LMOTS_SHA256_N32_W8 (4). */
    test_appendix_f_verifies(&tc1, 1);
    test_public_key_shape(&tc1, 1, 5u, 4u, 5u, 8u);
    test_every_signature_octet_is_load_bearing(&tc1, 1);
    test_message_and_public_key_are_load_bearing(&tc1, 1);
    test_inner_lms_level_verifies_standalone(&tc1, 1);
    test_structural_rejection(&tc1, 1);

    /* Case 2: L=2, LMS_SHA256_M32_H10 (6) + LMOTS_SHA256_N32_W4 (3). */
    test_appendix_f_verifies(&tc2, 2);
    test_public_key_shape(&tc2, 2, 6u, 3u, 10u, 4u);
    test_every_signature_octet_is_load_bearing(&tc2, 2);
    test_message_and_public_key_are_load_bearing(&tc2, 2);
    test_inner_lms_level_verifies_standalone(&tc2, 2);
    test_structural_rejection(&tc2, 2);

    /* Cross-case substitution: each key must reject the other's signature. */
    CHECK(ama_hss_verify(tc1.msg.data, tc1.msg.len, tc2.sig.data, tc2.sig.len, tc1.pub.data,
                         tc1.pub.len) != AMA_SUCCESS,
          "case 2's signature verified under case 1's public key");
    CHECK(ama_hss_verify(tc2.msg.data, tc2.msg.len, tc1.sig.data, tc1.sig.len, tc2.pub.data,
                         tc2.pub.len) != AMA_SUCCESS,
          "case 1's signature verified under case 2's public key");

    test_signing_is_reported_absent();

    free_case(&tc1);
    free_case(&tc2);
    free(g_corpus);

    printf("\n%d checks, %d failures\n", g_checks, g_failures);
    return g_failures == 0 ? 0 : 1;
}
