# Copyright (C) 2025-2026 Steel Security Advisors LLC
# SPDX-License-Identifier: Apache-2.0
"""
Auto-generated by ama_cryptography._build_sign at wheel build time.

DO NOT EDIT.  Any modification invalidates the import-time integrity
check (`ama_cryptography._self_test._verify_integrity`) and the
module enters the ERROR state on next import.

The (public_key, signature) pair below is the build-time Ed25519
signature over the SHA3-256 digest of the package's .py files.  The
private key was discarded immediately after signing — see
SECURITY.md "Module Integrity Verification" for the threat model.
"""

# SHA3-256 digest of the package's .py files at build time (raw 32 bytes,
# hex-encoded for embeddability).
INTEGRITY_DIGEST_HEX = "891d9eaad02a215e03b98026357f3b89d7971de72bd99f4cb9243983a4f338e4"

# SHA3-256 digest of the native library (libama_cryptography) at build time.
# This is what binds the shared object that performs every cryptographic
# operation into the same signature that covers the .py files — without it the
# signature attested to the Python wrapper only, and the implementation the
# wrapper calls into was covered by nothing.
INTEGRITY_NATIVE_DIGEST_HEX = "9af3c76454fb2f00a89831b1a87807875f7f915710d76805d7b347a96d52ddfe"

# Ephemeral build-time Ed25519 public key (raw 32 bytes, hex-encoded).
INTEGRITY_PUBKEY_HEX = "2a9c0b003a88450873c38c09dd2626d5f7f23d3c31b57c587b48ec15377cfe22"

# Ed25519 signature over SHA3-256(domain || py_digest || native_digest) — the
# v2 composite that makes the two digests inseparable.  See
# ama_cryptography._self_test._composite_integrity_message.
INTEGRITY_SIGNATURE_HEX = "be558f90207f30818934d99957adaacbd49732013077f98f3dc7470e664a85e3d4983aa458612330245c7753f2f4bc05be57ce3236776d254f55f94679ec4606"

# Build metadata — informational only, not part of the integrity contract.
BUILD_PIPELINE_VERSION = "2"
