"""
Auto-generated by ama_cryptography._build_sign at wheel build time.

DO NOT EDIT.  Any modification invalidates the import-time integrity
check (`ama_cryptography._self_test._verify_integrity`) and the
module enters the ERROR state on next import.

The (public_key, signature) pair below is the build-time Ed25519
signature over the SHA3-256 digest of the package's .py files.  The
private key was discarded immediately after signing — see
SECURITY.md "Module Integrity Verification" for the threat model.
"""

# SHA3-256 digest of the package's .py files at build time (raw 32 bytes,
# hex-encoded for embeddability).
INTEGRITY_DIGEST_HEX = "1afa581c66aeb349da5d38cc74816a6cae857c1b0c8ab99119789eab4e178f3b"

# Ephemeral build-time Ed25519 public key (raw 32 bytes, hex-encoded).
INTEGRITY_PUBKEY_HEX = "b2d3b0a19cee1e42e9046cd1f34685a441ddb7d7fae1599ffe6de5dcf6e1f721"

# Ed25519 signature over the raw digest above (raw 64 bytes, hex-encoded).
INTEGRITY_SIGNATURE_HEX = "e9c7c6a6d84a8d9cadca790e8dcf430381ab68959146990df284a755dd4e316720b39d0c188dd44f97a44ea9bc058f255c55c3cf702927b06049a6b8d5d75404"

# Build metadata — informational only, not part of the integrity contract.
BUILD_PIPELINE_VERSION = "1"
