homepage: "https://github.com/Steel-SecAdv-LLC/AMA-Cryptography"
language: c
primary_contact: "security@steelsecadv.com"
auto_ccs:
  - "ama-dev@steelsecadv.com"
main_repo: "https://github.com/Steel-SecAdv-LLC/AMA-Cryptography.git"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
