#!/usr/bin/env python3
# Copyright (C) 2025-2026 Steel Security Advisors LLC
# SPDX-License-Identifier: Apache-2.0
"""
INVARIANT-36 — no third-party cryptographic implementation in the validation path.

AMA is built from standardised primitives and its own code. That commitment is
stated in the README ("no custom ciphers ... zero external crypto deps") and it
holds for what the library *ships*: nothing links, loads or calls another
cryptographic library at runtime.

It did not hold for how the library was *checked*. The key-format conformance
corpus carried twelve PEM files generated by OpenSSL, vendored as the answer key
for EC PKCS#8 and SPKI on the reasoning that RFC 5915 and RFC 5480 publish no
worked examples. The files were static data and no build or test invoked
OpenSSL — but a competing implementation's output was nonetheless the thing
AMA's correctness was measured against, in AMA's own repository.

Two problems with that, one of principle and one of engineering:

* A project whose stated position is that it depends on no other cryptographic
  implementation should not depend on one to know whether it is right.
* An answer key taken from an implementation inherits that implementation's
  opinions, including its bugs and its non-conformances. A specification's
  worked example does not. This is the same lesson PR #378 learned on RFC 6979,
  where an "independent" reference normalised `s` because the C code did, and
  the two agreed by construction while both diverged from the RFC.

RFC 9500 §2.3 ("Standard Public Key Cryptography (PKCS) Test Keys", December
2023) publishes exactly the EC keys that gap needed, and
``tests/ref_keyformat.py`` supplies a second encoder written from the RFCs' own
ASN.1 for everything the documents do not print. The OpenSSL corpus is gone.

This checker is what stops it coming back, because "just this once, to cover a
gap" is precisely how it arrived.

What is checked
---------------
1. **No test or development tool invokes an external cryptographic binary.**
   ``openssl``, ``gpg``, ``certtool``, ``pkcs11-tool`` and friends, in any
   ``subprocess`` call or shell string under ``tests/`` or ``tools/``.
2. **Every vendored key-format record names a standards-body source.** The
   ``source.url`` of each corpus file must be on ``rfc-editor.org`` or
   ``ietf.org``.
3. **The reference encoder stays independent.** ``tests/ref_keyformat.py`` must
   import nothing from ``ama_cryptography`` — a reference that imports the
   encoder it checks agrees with it by construction and proves nothing.

What is deliberately *not* checked
----------------------------------
* ``wycheproof_vectors/`` and ``tests/kat/``'s NIST ACVP corpora. These are
  published *test-vector suites* — adversarial inputs with expected verdicts —
  not another implementation's key output presented as ground truth. Their
  provenance has its own gates (``tools/refresh_wycheproof_corpus.py`` and
  ``.github/workflows/corpus-provenance.yml``).
* ``ama_cryptography/legacy_compat.py``, which shells out to ``openssl ts`` for
  RFC 3161 timestamping. That is a shipped interop feature with its own history
  and its own removal decision to make; it is named here so that it is a
  *recorded* exception rather than an oversight, and it is outside this
  checker's scope by construction (it scans ``tests/`` and ``tools/`` only).

Exit code:
    0  no third-party cryptographic implementation in the validation path
    1  a violation was found
"""

from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

#: Executables that are another cryptographic implementation. Matched as whole
#: words so a filename like `openssl_notes.md` or a variable named `gpg_path`
#: does not trip the check — only an actual invocation does.
CRYPTO_BINARIES = (
    "openssl",
    "gpg",
    "gpg2",
    "certtool",
    "pkcs11-tool",
    "keytool",
    "libressl",
    "boringssl",
    "nss-tool",
    "certutil",
)

#: Hosts a vendored answer key may come from: the RFC archive and the IETF's.
STANDARDS_HOSTS = ("rfc-editor.org", "ietf.org")

#: Trees scanned for invocations. `ama_cryptography/` is excluded on purpose —
#: see "What is deliberately not checked" above.
SCAN_ROOTS = ("tests", "tools")

KEYFORMAT_CORPUS = REPO / "tests" / "kat" / "keyformats"
REFERENCE_ENCODER = REPO / "tests" / "ref_keyformat.py"

_BINARY_RE = re.compile(r"\b(" + "|".join(CRYPTO_BINARIES) + r")\b")


def _rel(path: Path) -> str:
    """Repo-relative when the path is in the tree, absolute otherwise.

    The scan functions take a root so the tests can drive them over a temporary
    tree; those paths are outside the repository, and ``relative_to`` raises on
    them. Mirrors ``tools/check_version_consistency.py``.
    """
    try:
        return str(path.relative_to(REPO))
    except ValueError:
        return str(path)


def _literal_strings(node: ast.AST) -> list[str]:
    """Every string constant inside an expression tree.

    Covers ``["openssl", "genpkey"]``, ``"openssl genpkey"`` and the elements of
    a starred list, which is how the removed generator actually spelled it.
    """
    out: list[str] = []
    for child in ast.walk(node):
        if isinstance(child, ast.Constant) and isinstance(child.value, str):
            out.append(child.value)
    return out


def scan_for_binary_invocations(repo: Path = REPO) -> list[str]:
    """Find calls that would run another cryptographic implementation.

    Works on the AST rather than by grepping, so a mention in a docstring or a
    comment — of which this repository has many, mostly of the form "replaces
    OpenSSL X" — is not a finding. Only the arguments of a call are inspected.
    """
    problems: list[str] = []
    for root in SCAN_ROOTS:
        base = repo / root
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*.py")):
            if any(part in {"__pycache__", "build"} for part in path.parts):
                continue
            rel = _rel(path)
            try:
                tree = ast.parse(path.read_text(encoding="utf-8"))
            except (SyntaxError, UnicodeDecodeError) as exc:  # pragma: no cover
                problems.append(f"{rel}: could not parse ({exc})")
                continue
            for node in ast.walk(tree):
                if not isinstance(node, ast.Call):
                    continue
                target = node.func
                name = (
                    target.attr if isinstance(target, ast.Attribute)
                    else target.id if isinstance(target, ast.Name)
                    else ""
                )
                if name not in {"run", "Popen", "call", "check_call",
                                "check_output", "system"}:
                    continue
                for text in _literal_strings(node):
                    match = _BINARY_RE.search(text)
                    if match:
                        problems.append(
                            f"{rel}:{node.lineno}: invokes {match.group(1)!r}. "
                            "AMA's correctness is not measured against another "
                            "cryptographic implementation (INVARIANT-36); use a "
                            "published specification vector or "
                            "tests/ref_keyformat.py."
                        )
                        break
    return problems


def scan_corpus_sources(corpus: Path = KEYFORMAT_CORPUS) -> list[str]:
    """Every vendored record must trace to a standards document."""
    problems: list[str] = []
    if not corpus.is_dir():
        return [f"{corpus} is missing"]
    files = sorted(corpus.glob("*.json"))
    if not files:
        return [f"{corpus} contains no corpus files"]
    for path in files:
        rel = _rel(path)
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            problems.append(f"{rel}: not valid JSON ({exc})")
            continue
        url = str(data.get("source", {}).get("url", ""))
        if not any(host in url for host in STANDARDS_HOSTS):
            problems.append(
                f"{rel}: source.url is {url!r}, which is not a standards-body "
                f"archive ({', '.join(STANDARDS_HOSTS)}). A vendored answer key "
                "must be a specification's own worked example."
            )
    # A directory under the corpus is how the OpenSSL files were carried.
    for child in sorted(corpus.iterdir()):
        if child.is_dir():
            problems.append(
                f"{_rel(child)}: unexpected directory in the corpus. "
                "Every record lives in a JSON file naming the document it came "
                "from; a directory of key files is how third-party material "
                "entered this tree before."
            )
    return problems


def check_reference_encoder(path: Path = REFERENCE_ENCODER) -> list[str]:
    """The reference must stand on the specification, not on the code it checks."""
    if not path.is_file():
        return [f"{_rel(path)} is missing; it is what replaced the "
                "third-party corpus and the tests depend on it"]
    imported: set[str] = set()
    for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
        if isinstance(node, ast.Import):
            imported.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module.split(".")[0])
    if "ama_cryptography" in imported:
        return [
            f"{_rel(path)} imports ama_cryptography. A reference that "
            "imports the encoder it checks agrees with it by construction and "
            "proves nothing — the RFC 6979 lesson, in one line of import."
        ]
    return []


def main() -> int:
    sections = (
        ("external cryptographic binaries in tests/ and tools/",
         scan_for_binary_invocations()),
        ("vendored corpus provenance", scan_corpus_sources()),
        ("reference-encoder independence", check_reference_encoder()),
    )
    failures = [(title, problems) for title, problems in sections if problems]
    for title, problems in sections:
        if not problems:
            print(f"OK    {title}")
    if failures:
        print("\nFAIL: INVARIANT-36 — a third-party cryptographic implementation "
              "is in the validation path.", file=sys.stderr)
        for title, problems in failures:
            print(f"  {title}:", file=sys.stderr)
            for problem in problems:
                print(f"    - {problem}", file=sys.stderr)
        return 1
    print("\nINVARIANT-36 holds: AMA is checked against specifications and its own "
          "reference encoder, not against another implementation.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
