#!/usr/bin/env python3
# Copyright (C) 2025-2026 Steel Security Advisors LLC
# SPDX-License-Identifier: Apache-2.0
"""
Generate visual diagrams for AMA Cryptography documentation.

Creates (in ../assets/):
  - test_coverage.png             (test distribution, anchored to
                                   docs/METRICS_REPORT.md)
  - ethical_binding.png           (Omni-Code ethical vector diagram)
  - quantum_comparison.png        (classical vs quantum security bits)

The 4-layer defense-in-depth diagram (assets/defense_layers.png) is
generated by tools/generate_dashboards.py — the canonical owner of
that asset. Do not duplicate it here.

Three charts were removed on 2026-07-29 rather than regenerated:
performance_comparison.png, package_performance.png and
monitoring_overhead.png. None was referenced by any document in the
repository, so each cost build time and ~450 KB of history while being
reachable only by opening the assets directory directly. The first also
rendered an impossible result — it charted Python-via-ctypes as 20%
*faster* than raw C, because its raw-C side came from a hardcoded
RAW_C_MEDIANS_US snapshot while its ctypes side loaded live data, so the
two halves described different hosts. An unreferenced chart that is also
wrong is not an asset. Regenerating any of them means restoring the
function AND adding the document reference that justifies it.
"""

import json
import re
from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np

# Set style
plt.style.use("seaborn-v0_8-whitegrid")
plt.rcParams["font.family"] = "DejaVu Sans"
plt.rcParams["font.size"] = 11

REPO_ROOT = Path(__file__).parent.parent

# Version read from the package, not written here. This footer used to carry a
# hardcoded "v3.0.0" against a 3.4.0 library — the same defect that froze the
# dashboard PNGs at v2.1.5 — so a regenerated chart asserted a version it had
# no way to know had moved.
_PKG_VERSION = re.search(
    r'^__version__\s*=\s*"([^"]+)"',
    (REPO_ROOT / "ama_cryptography" / "__init__.py").read_text(encoding="utf-8"),
    re.M,
).group(1)
ASSETS_DIR = REPO_ROOT / "assets"
ASSETS_DIR.mkdir(exist_ok=True)

PHASE0_JSON = REPO_ROOT / "benchmarks" / "phase0_baseline_results.json"
TESTS_DIR = REPO_ROOT / "tests"


def _load_phase0_medians():
    """Load median latencies (microseconds) from the checked-in
    Python/ctypes-path benchmark snapshot.

    Returns a dict keyed by the operation labels used inside
    `phase0_baseline_results.json`. Charts that depend on these
    numbers should call this loader rather than re-typing literals,
    so the chart cannot drift out of sync with the JSON snapshot.
    """
    with open(PHASE0_JSON) as fh:
        raw = json.load(fh)
    return {name: entry["median_us"] for name, entry in raw.items()}


# Raw C medians (microseconds) from `build/bin/benchmark_c_raw --json`.
# This source is build-time-only — the harness binary and its JSON output
# are not checked into the repository, so these literals are a snapshot
# transcribed from one run of the harness on Linux x86_64 with AVX2.
# Refresh by rebuilding (cmake --build build --target benchmark_c_raw)
# and rerunning `LD_LIBRARY_PATH=build/lib build/bin/benchmark_c_raw --json`.
RAW_C_MEDIANS_US = {
    "ed25519_sign": 90.0,
    "ed25519_verify": 129.0,
    "mldsa65_sign": 348.0,
    "mldsa65_verify": 146.0,
}


# Category buckets for the test-coverage chart. Each entry is
# (display_label, list_of_filename_substring_predicates). A test file
# (basename) is assigned to the FIRST category whose predicate matches.
# Files that match no predicate are tracked separately as uncategorized
# (returned from `_count_test_functions_by_category()` as the third
# tuple element) and are NOT included in the bucketed counts or the
# chart's `total_tests`. `create_test_coverage()` surfaces any such
# files to the build log so a new `test_*.py` added without a matching
# rule is visible at chart-generation time instead of silently dropping
# off the chart.
_TEST_CATEGORY_RULES = [
    (
        "Core Crypto\n& NIST KATs",
        (
            "nist_kat",
            "pqc_kat",
            "simd_kat",
            "aes_gcm",
            "sha3",
            "hkdf",
            "ed25519",
            "hybrid_combiner",
            "secure_channel",
            "crypto_api",
            "crypto_package_layers",
            "rfc3161",
            "integrity",
            "frost",
            "differential",
            "monitor",
            "new_primitives",
            "basic",
        ),
    ),
    (
        "PQC Backends\n& Integration",
        (
            "pqc_backend",
            "adversarial_pqc",
            "integration_e2e",
            "comprehensive_system",
            "cli_entry",
            "import",
            "smoke_import",
            "lazy_imports",
            "priority_integration",
            "demonstration",
            "prior_session_coverage",
            "code_quality_additions",
            "pr224_followup",
            "exceptions",
            "invariant_upgrades",
            "self_test_branches",
            "self_test_coverage",
        ),
    ),
    (
        "Key Management\n& Rotation",
        (
            "hd_key_derivation",
            "key_management",
            "key_rotation",
            "hsm",
            "nonce_tracker",
            "session",
        ),
    ),
    (
        "Memory Security\n& Fuzzing",
        (
            "secure_memory",
            "fuzzing",
            "penetration",
            "adversarial_security",
            "fips140",
            "security_fixes",
            "memory_security",
        ),
    ),
    (
        "Performance\n& Monitoring",
        (
            "performance",
            "adaptive_posture",
            "double_helix",
            "lyapunov",
            "equations",
            "numeric",
        ),
    ),
]
_DEF_TEST_RE = re.compile(r"^\s*def test_", re.MULTILINE)


def _classify_test_file(basename):
    """Return the display_label of the first category whose predicate
    list matches `basename` (a `test_*.py` filename), or None if no
    rule matches."""
    for label, predicates in _TEST_CATEGORY_RULES:
        if any(p in basename for p in predicates):
            return label
    return None


def _count_test_functions_by_category():
    """Walk `tests/test_*.py`, count `def test_` matches per file, and
    bucket each file into one of `_TEST_CATEGORY_RULES`. Returns
    (counts_in_rule_order, total, unbucketed_files).

    `def test_` matches in `conftest.py` are intentionally excluded —
    they are pytest fixtures, not tests. This count therefore equals
    the 2,026-across-69 subset of docs/METRICS_REPORT.md's headline
    2,028-across-70 figure.
    """
    counts = [0] * len(_TEST_CATEGORY_RULES)
    label_to_idx = {label: i for i, (label, _) in enumerate(_TEST_CATEGORY_RULES)}
    unbucketed = []
    for path in sorted(TESTS_DIR.glob("test_*.py")):
        n = len(_DEF_TEST_RE.findall(path.read_text(encoding="utf-8")))
        label = _classify_test_file(path.name)
        if label is None:
            unbucketed.append((path.name, n))
            continue
        counts[label_to_idx[label]] += n
    return counts, sum(counts), unbucketed


def create_test_coverage():
    """Create enhanced test coverage visualization with percentages and cumulative data."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5), gridspec_kw={"width_ratios": [2, 1]})

    # Categories and counts are computed live from the working tree.
    # `_count_test_functions_by_category()` walks tests/test_*.py and
    # buckets each file into one of `_TEST_CATEGORY_RULES` (defined at
    # module scope) by filename predicate; `def test_` matches per file
    # are counted via regex. conftest.py is excluded (its `def test_`
    # entries are pytest fixtures, not tests).
    categories = [label for label, _ in _TEST_CATEGORY_RULES]
    test_counts, total_tests, unbucketed = _count_test_functions_by_category()
    # File count is derived once here and reused in both the suptitle
    # and the footer so they cannot disagree if tests are added or
    # removed. It matches the set walked by `_count_test_functions_by_category()`.
    n_files = len(list(TESTS_DIR.glob("test_*.py")))
    if unbucketed:
        # Surface in the build log so a new test file added without a
        # matching rule is noticed instead of silently dropped.
        print("WARN: test files without a category rule (will be excluded " "from chart):")
        for name, n in unbucketed:
            print(f"  - {name} ({n} tests)")
    percentages = (
        [100 * c / total_tests for c in test_counts] if total_tests else [0] * len(categories)
    )
    colors = ["#22C55E", "#3B82F6", "#8B5CF6", "#F59E0B", "#EF4444"]

    # === Left Panel: Horizontal bar chart with percentages ===
    bars = ax1.barh(categories, test_counts, color=colors, edgecolor="white", linewidth=2)

    ax1.set_xlabel("Number of Tests", fontsize=11)
    ax1.set_title("Test Distribution by Category", fontsize=12, fontweight="bold")
    ax1.set_xlim(0, max(test_counts) * 1.25)

    # Add count and percentage labels
    for bar, val, pct in zip(bars, test_counts, percentages):
        ax1.text(
            bar.get_width() + 3,
            bar.get_y() + bar.get_height() / 2,
            f"{val} ({pct:.1f}%)",
            ha="left",
            va="center",
            fontsize=10,
            fontweight="bold",
        )

    ax1.grid(True, alpha=0.3, axis="x")

    # === Right Panel: Cumulative coverage line chart ===
    cumulative = np.cumsum(test_counts)
    cumulative_pct = 100 * cumulative / total_tests
    y_pos = np.arange(len(categories))

    ax2.plot(
        cumulative_pct,
        y_pos,
        "o-",
        color="#3B82F6",
        linewidth=2.5,
        markersize=10,
        markeredgecolor="white",
        markeredgewidth=2,
    )
    ax2.fill_betweenx(y_pos, 0, cumulative_pct, alpha=0.2, color="#3B82F6")

    # Add percentage annotations
    for i, (cum, pct) in enumerate(zip(cumulative, cumulative_pct)):
        ax2.annotate(
            f"{pct:.0f}%\n({cum})",
            (pct, i),
            textcoords="offset points",
            xytext=(8, 0),
            ha="left",
            fontsize=9,
            fontweight="bold",
        )

    ax2.set_yticks(y_pos)
    ax2.set_yticklabels(categories, fontsize=9)
    ax2.set_xlabel("Cumulative Coverage (%)", fontsize=11)
    ax2.set_title("Cumulative Test Coverage", fontsize=12, fontweight="bold")
    ax2.set_xlim(0, 115)
    ax2.grid(True, alpha=0.3)

    # Overall title
    fig.suptitle(
        f"Test Suite Coverage: {total_tests} Tests Across {n_files} `test_*.py` Files",
        fontsize=14,
        fontweight="bold",
        y=1.02,
    )

    # Summary box
    fig.text(
        0.5,
        -0.06,
        f"v{_PKG_VERSION} | Chart: {total_tests} test functions across "
        f"{n_files} test_*.py files "
        "(scanned live at chart-generation time by "
        "_count_test_functions_by_category(); excludes conftest.py). "
        "Independent reproduction: docs/METRICS_REPORT.md.",
        ha="center",
        fontsize=9,
        color="#6B7280",
        bbox=dict(boxstyle="round,pad=0.4", facecolor="#F3F4F6", edgecolor="#D1D5DB"),
    )

    plt.tight_layout()
    plt.savefig(
        ASSETS_DIR / "test_coverage.png",
        dpi=150,
        bbox_inches="tight",
        facecolor="white",
        edgecolor="none",
    )
    plt.close()
    print(f"Created: {ASSETS_DIR / 'test_coverage.png'}")


def create_ethical_binding_flow():
    """Create comprehensive ethical binding diagram showing 4 pillars with weights."""
    fig, ax = plt.subplots(figsize=(18, 12))
    ax.set_xlim(0, 18)
    ax.set_ylim(0, 12)
    ax.axis("off")

    # Title
    ax.text(
        9,
        11.5,
        "Ethical Vector Cryptographic Binding",
        ha="center",
        fontsize=20,
        fontweight="bold",
        color="#1F2937",
    )
    ax.text(
        9,
        10.9,
        "4 Omni-Code Ethical Pillars bound to keys and signatures via SHA3-256 + HKDF",
        ha="center",
        fontsize=12,
        color="#6B7280",
    )

    # Define the 4 pillars with their triads
    triads = [
        (
            "Omniscient: Wisdom",
            "#3B82F6",
            "Verification Layer",
            [
                ("verification", "Complete verification"),
                ("detection", "Multi-dimensional detection"),
                ("validation", "Data validation"),
            ],
        ),
        (
            "Omnipotent: Agency",
            "#22C55E",
            "Cryptographic Generation",
            [
                ("strength", "Maximum strength"),
                ("generation", "Key generation"),
                ("protection", "Real-time protection"),
            ],
        ),
        (
            "Omnidirectional: Geography",
            "#0EA5E9",
            "Defense-in-Depth",
            [
                ("defense", "Multi-layer defense"),
                ("temporal", "Temporal binding"),  # not integrity: TSA genTime is unauthenticated
                ("coverage", "Attack surface coverage"),
            ],
        ),
        (
            "Omnibenevolent: Integrity",
            "#8B5CF6",
            "Ethical Constraints",
            [
                ("ethics", "Ethical foundation"),
                ("correctness", "Mathematical correctness"),
                ("hybrid", "Hybrid security"),
            ],
        ),
    ]

    # Draw 4 triad boxes in 2x2 grid on the left
    triad_positions = [(1.8, 8.2), (5.5, 8.2), (1.8, 4.8), (5.5, 4.8)]

    for idx, ((name, color, subtitle, pillars), (x, y)) in enumerate(zip(triads, triad_positions)):
        # Triad box
        rect = mpatches.FancyBboxPatch(
            (x - 1.6, y - 1.5),
            3.2,
            3.0,
            boxstyle="round,pad=0.02,rounding_size=0.15",
            facecolor=color,
            edgecolor="white",
            linewidth=2,
            alpha=0.15,
        )
        ax.add_patch(rect)

        # Triad header
        header_rect = mpatches.FancyBboxPatch(
            (x - 1.5, y + 1.0),
            3.0,
            0.45,
            boxstyle="round,pad=0.01,rounding_size=0.1",
            facecolor=color,
            edgecolor="white",
            linewidth=1,
        )
        ax.add_patch(header_rect)
        ax.text(
            x,
            y + 1.22,
            name,
            ha="center",
            va="center",
            fontsize=10,
            fontweight="bold",
            color="white",
        )
        ax.text(x, y + 0.75, f"({subtitle})", ha="center", va="center", fontsize=8, color="#374151")

        # Pillars
        for i, (pillar_name, pillar_desc) in enumerate(pillars):
            py = y + 0.3 - i * 0.55
            ax.text(
                x - 1.4,
                py,
                f"{pillar_name}",
                ha="left",
                va="center",
                fontsize=9,
                fontweight="bold",
                color="#1F2937",
            )
            ax.text(
                x + 1.5,
                py,
                "w=1.0",
                ha="right",
                va="center",
                fontsize=8,
                color=color,
                fontweight="bold",
            )
            ax.text(
                x - 1.4,
                py - 0.22,
                f"  {pillar_desc}",
                ha="left",
                va="center",
                fontsize=7,
                color="#6B7280",
            )

    # Aggregator box: Balanced Ethical Vector
    agg_x, agg_y = 9.2, 6.5
    agg_rect = mpatches.FancyBboxPatch(
        (agg_x - 1.3, agg_y - 0.8),
        2.6,
        1.6,
        boxstyle="round,pad=0.02,rounding_size=0.1",
        facecolor="#F3F4F6",
        edgecolor="#9CA3AF",
        linewidth=2,
    )
    ax.add_patch(agg_rect)
    ax.text(
        agg_x,
        agg_y + 0.35,
        "Balanced Vector",
        ha="center",
        va="center",
        fontsize=10,
        fontweight="bold",
        color="#1F2937",
    )
    ax.text(agg_x, agg_y - 0.05, "4 pillars", ha="center", va="center", fontsize=9, color="#374151")
    ax.text(
        agg_x,
        agg_y - 0.4,
        "each w = 1.0",
        ha="center",
        va="center",
        fontsize=9,
        color="#374151",
        fontweight="bold",
    )

    # Draw arrows from triads to aggregator
    # Arrow styling is set inline in annotate() calls below
    for x, y in triad_positions:
        ax.annotate(
            "",
            xy=(agg_x - 1.3, agg_y),
            xytext=(x + 1.6, y),
            arrowprops=dict(
                arrowstyle="->", color="#9CA3AF", lw=1.2, connectionstyle="arc3,rad=0.1"
            ),
        )

    # Cryptographic binding pipeline on the right
    pipeline_y = 6.5
    pipeline_boxes = [
        (11.5, "JSON Encode", "sorted keys", "#6366F1"),
        (13.5, "SHA3-256", "H(ethical_json)", "#3B82F6"),
        (15.5, "128-bit Sig", "H(E)[:16]", "#0EA5E9"),
    ]

    # Arrow from aggregator to pipeline
    ax.annotate(
        "",
        xy=(11.5 - 0.9, pipeline_y),
        xytext=(agg_x + 1.3, agg_y),
        arrowprops=dict(arrowstyle="->", color="#374151", lw=2),
    )

    for px, label, sublabel, color in pipeline_boxes:
        rect = mpatches.FancyBboxPatch(
            (px - 0.85, pipeline_y - 0.6),
            1.7,
            1.2,
            boxstyle="round,pad=0.02,rounding_size=0.1",
            facecolor=color,
            edgecolor="white",
            linewidth=2,
        )
        ax.add_patch(rect)
        ax.text(
            px,
            pipeline_y + 0.15,
            label,
            ha="center",
            va="center",
            fontsize=10,
            fontweight="bold",
            color="white",
        )
        ax.text(
            px,
            pipeline_y - 0.2,
            sublabel,
            ha="center",
            va="center",
            fontsize=8,
            color="white",
            alpha=0.9,
        )

    # Arrows between pipeline boxes
    for i in range(len(pipeline_boxes) - 1):
        x1 = pipeline_boxes[i][0] + 0.85
        x2 = pipeline_boxes[i + 1][0] - 0.85
        ax.annotate(
            "",
            xy=(x2, pipeline_y),
            xytext=(x1, pipeline_y),
            arrowprops=dict(arrowstyle="->", color="#374151", lw=2),
        )

    # Final output boxes
    output_y1, output_y2 = 8.5, 4.5

    # Arrow from 128-bit sig to outputs
    ax.annotate(
        "",
        xy=(16.2, output_y1 - 0.5),
        xytext=(15.5, pipeline_y + 0.6),
        arrowprops=dict(arrowstyle="->", color="#22C55E", lw=2),
    )
    ax.annotate(
        "",
        xy=(16.2, output_y2 + 0.5),
        xytext=(15.5, pipeline_y - 0.6),
        arrowprops=dict(arrowstyle="->", color="#22C55E", lw=2),
    )

    # HKDF Context output
    rect1 = mpatches.FancyBboxPatch(
        (15.3, output_y1 - 0.5),
        2.4,
        1.0,
        boxstyle="round,pad=0.02,rounding_size=0.1",
        facecolor="#22C55E",
        edgecolor="white",
        linewidth=2,
    )
    ax.add_patch(rect1)
    ax.text(
        16.5,
        output_y1 + 0.1,
        "HKDF Context",
        ha="center",
        va="center",
        fontsize=10,
        fontweight="bold",
        color="white",
    )
    ax.text(
        16.5,
        output_y1 - 0.2,
        "Key Derivation",
        ha="center",
        va="center",
        fontsize=8,
        color="white",
        alpha=0.9,
    )

    # Signature Message output
    rect2 = mpatches.FancyBboxPatch(
        (15.3, output_y2 - 0.5),
        2.4,
        1.0,
        boxstyle="round,pad=0.02,rounding_size=0.1",
        facecolor="#22C55E",
        edgecolor="white",
        linewidth=2,
    )
    ax.add_patch(rect2)
    ax.text(
        16.5,
        output_y2 + 0.1,
        "Signature Msg",
        ha="center",
        va="center",
        fontsize=10,
        fontweight="bold",
        color="white",
    )
    ax.text(
        16.5,
        output_y2 - 0.2,
        "Ed25519 + ML-DSA-65",
        ha="center",
        va="center",
        fontsize=8,
        color="white",
        alpha=0.9,
    )

    # Sum annotation
    ax.text(
        9.2,
        5.4,
        "Sum: 12 x 1.0 = 12.0",
        ha="center",
        va="center",
        fontsize=11,
        fontweight="bold",
        color="#059669",
        bbox=dict(boxstyle="round,pad=0.3", facecolor="#DCFCE7", edgecolor="#22C55E"),
    )

    # Caption
    ax.text(
        9,
        0.8,
        "The 4 Omni-Code Ethical Pillars form a balanced vector (each w = 3.0, total = 12.0).\n"
        "This vector is hashed with SHA3-256 and a 128-bit signature is injected into HKDF context and signature messages,\n"
        "cryptographically binding keys and signatures to an explicit ethical profile. This is binding, not enforcement.",
        ha="center",
        fontsize=10,
        style="italic",
        color="#6B7280",
    )

    plt.tight_layout()
    plt.savefig(
        ASSETS_DIR / "ethical_binding.png",
        dpi=150,
        bbox_inches="tight",
        facecolor="white",
        edgecolor="none",
    )
    plt.close()
    print(f"Created: {ASSETS_DIR / 'ethical_binding.png'}")


def create_quantum_comparison():
    """Create quantum vs classical security comparison."""
    fig, ax = plt.subplots(figsize=(10, 6))

    algorithms = [
        "RSA-2048\n(Classical)",
        "ECDSA-256\n(Classical)",
        "Ed25519\n(Classical)",
        "ML-DSA-65\n(Quantum-Resistant)",
    ]

    # Security levels (bits) - classical vs quantum
    classical_security = [112, 128, 128, 192]
    quantum_security = [0, 0, 0, 192]  # 0 means broken by quantum

    x = np.arange(len(algorithms))
    width = 0.35

    ax.bar(
        x - width / 2,
        classical_security,
        width,
        label="Classical Security",
        color="#3B82F6",
        edgecolor="white",
        linewidth=2,
    )
    ax.bar(
        x + width / 2,
        quantum_security,
        width,
        label="Quantum Security",
        color="#8B5CF6",
        edgecolor="white",
        linewidth=2,
    )

    ax.set_ylabel("Security Level (bits)", fontsize=12)
    ax.set_title("Classical vs Quantum Security Comparison", fontsize=14, fontweight="bold")
    ax.set_xticks(x)
    ax.set_xticklabels(algorithms)
    ax.legend(loc="upper left")
    ax.set_ylim(0, 250)

    # Add "BROKEN" labels for quantum-vulnerable algorithms
    for i, (c, q) in enumerate(zip(classical_security, quantum_security)):
        ax.text(
            i - width / 2, c + 5, f"{c}", ha="center", va="bottom", fontsize=10, fontweight="bold"
        )
        if q == 0:
            ax.text(
                i + width / 2,
                10,
                "BROKEN",
                ha="center",
                va="bottom",
                fontsize=9,
                fontweight="bold",
                color="#EF4444",
                rotation=90,
            )
        else:
            ax.text(
                i + width / 2,
                q + 5,
                f"{q}",
                ha="center",
                va="bottom",
                fontsize=10,
                fontweight="bold",
            )

    # Add annotation
    fig.text(
        0.5,
        -0.02,
        "ML-DSA-65 (Dilithium) provides 192-bit security against both classical and quantum attacks",
        ha="center",
        fontsize=10,
        style="italic",
        color="#6B7280",
    )

    plt.tight_layout()
    plt.savefig(
        ASSETS_DIR / "quantum_comparison.png",
        dpi=150,
        bbox_inches="tight",
        facecolor="white",
        edgecolor="none",
    )
    plt.close()
    print(f"Created: {ASSETS_DIR / 'quantum_comparison.png'}")


if __name__ == "__main__":
    print("Generating AMA Cryptography visual diagrams...")
    print("=" * 50)

    # defense_layers.png is owned by tools/generate_dashboards.py
    create_test_coverage()
    create_ethical_binding_flow()
    create_quantum_comparison()

    print("=" * 50)
    print(f"All visuals saved to: {ASSETS_DIR}")
