#!/usr/bin/env python3
"""
Generate visual diagrams for AMA Cryptography documentation.

Creates (in ../assets/):
  - performance_comparison.png    (hybrid signature, 3-panel)
  - package_performance.png       (per-layer latency breakdown)
  - monitoring_overhead.png       (3R overhead pie chart)
  - test_coverage.png             (test distribution, anchored to
                                   docs/METRICS_REPORT.md)
  - ethical_binding.png           (Omni-Code ethical vector diagram)
  - quantum_comparison.png        (classical vs quantum security bits)

The 4-layer defense-in-depth diagram (assets/defense_layers.png) is
generated by tools/generate_dashboards.py — the canonical owner of
that asset. Do not duplicate it here.
"""

import json
import re
from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np

# Set style
plt.style.use("seaborn-v0_8-whitegrid")
plt.rcParams["font.family"] = "DejaVu Sans"
plt.rcParams["font.size"] = 11

REPO_ROOT = Path(__file__).parent.parent
ASSETS_DIR = REPO_ROOT / "assets"
ASSETS_DIR.mkdir(exist_ok=True)

PHASE0_JSON = REPO_ROOT / "benchmarks" / "phase0_baseline_results.json"
TESTS_DIR = REPO_ROOT / "tests"


def _load_phase0_medians():
    """Load median latencies (microseconds) from the checked-in
    Python/ctypes-path benchmark snapshot.

    Returns a dict keyed by the operation labels used inside
    `phase0_baseline_results.json`. Charts that depend on these
    numbers should call this loader rather than re-typing literals,
    so the chart cannot drift out of sync with the JSON snapshot.
    """
    with open(PHASE0_JSON) as fh:
        raw = json.load(fh)
    return {name: entry["median_us"] for name, entry in raw.items()}


# Raw C medians (microseconds) from `build/bin/benchmark_c_raw --json`.
# This source is build-time-only — the harness binary and its JSON output
# are not checked into the repository, so these literals are a snapshot
# transcribed from one run of the harness on Linux x86_64 with AVX2.
# Refresh by rebuilding (cmake --build build --target benchmark_c_raw)
# and rerunning `LD_LIBRARY_PATH=build/lib build/bin/benchmark_c_raw --json`.
RAW_C_MEDIANS_US = {
    "ed25519_sign": 90.0,
    "ed25519_verify": 129.0,
    "mldsa65_sign": 348.0,
    "mldsa65_verify": 146.0,
}


# Category buckets for the test-coverage chart. Each entry is
# (display_label, list_of_filename_substring_predicates). A test file
# (basename) is assigned to the FIRST category whose predicate matches.
# Files that match no predicate are tracked separately as uncategorized
# (returned from `_count_test_functions_by_category()` as the third
# tuple element) and are NOT included in the bucketed counts or the
# chart's `total_tests`. `create_test_coverage()` surfaces any such
# files to the build log so a new `test_*.py` added without a matching
# rule is visible at chart-generation time instead of silently dropping
# off the chart.
_TEST_CATEGORY_RULES = [
    (
        "Core Crypto\n& NIST KATs",
        (
            "nist_kat",
            "pqc_kat",
            "simd_kat",
            "aes_gcm",
            "sha3",
            "hkdf",
            "ed25519",
            "hybrid_combiner",
            "secure_channel",
            "crypto_api",
            "crypto_package_layers",
            "rfc3161",
            "integrity",
            "frost",
            "differential",
            "monitor",
            "new_primitives",
            "basic",
        ),
    ),
    (
        "PQC Backends\n& Integration",
        (
            "pqc_backend",
            "adversarial_pqc",
            "integration_e2e",
            "comprehensive_system",
            "cli_entry",
            "import",
            "smoke_import",
            "lazy_imports",
            "priority_integration",
            "demonstration",
            "prior_session_coverage",
            "code_quality_additions",
            "pr224_followup",
            "exceptions",
            "invariant_upgrades",
            "self_test_branches",
            "self_test_coverage",
        ),
    ),
    (
        "Key Management\n& Rotation",
        (
            "hd_key_derivation",
            "key_management",
            "key_rotation",
            "hsm",
            "nonce_tracker",
            "session",
        ),
    ),
    (
        "Memory Security\n& Fuzzing",
        (
            "secure_memory",
            "fuzzing",
            "penetration",
            "adversarial_security",
            "fips140",
            "security_fixes",
            "memory_security",
        ),
    ),
    (
        "Performance\n& Monitoring",
        (
            "performance",
            "adaptive_posture",
            "double_helix",
            "lyapunov",
            "equations",
            "numeric",
        ),
    ),
]
_DEF_TEST_RE = re.compile(r"^\s*def test_", re.MULTILINE)


def _classify_test_file(basename):
    """Return the display_label of the first category whose predicate
    list matches `basename` (a `test_*.py` filename), or None if no
    rule matches."""
    for label, predicates in _TEST_CATEGORY_RULES:
        if any(p in basename for p in predicates):
            return label
    return None


def _count_test_functions_by_category():
    """Walk `tests/test_*.py`, count `def test_` matches per file, and
    bucket each file into one of `_TEST_CATEGORY_RULES`. Returns
    (counts_in_rule_order, total, unbucketed_files).

    `def test_` matches in `conftest.py` are intentionally excluded —
    they are pytest fixtures, not tests. This count therefore equals
    the 2,026-across-69 subset of docs/METRICS_REPORT.md's headline
    2,028-across-70 figure.
    """
    counts = [0] * len(_TEST_CATEGORY_RULES)
    label_to_idx = {label: i for i, (label, _) in enumerate(_TEST_CATEGORY_RULES)}
    unbucketed = []
    for path in sorted(TESTS_DIR.glob("test_*.py")):
        n = len(_DEF_TEST_RE.findall(path.read_text(encoding="utf-8")))
        label = _classify_test_file(path.name)
        if label is None:
            unbucketed.append((path.name, n))
            continue
        counts[label_to_idx[label]] += n
    return counts, sum(counts), unbucketed


def create_performance_comparison():
    """Hybrid signature performance: Raw C vs Python ctypes.

    Compares the native C library path against the Python ctypes path
    for the hybrid (Ed25519 + ML-DSA-65) signature pipeline. Both paths
    use the exact same underlying C primitives; the ctypes path adds
    marshalling overhead.

    Data flow:
      - Python ctypes side: loaded at runtime from
        `benchmarks/phase0_baseline_results.json` (checked in).
      - Raw C side: literals in `RAW_C_MEDIANS_US` at module scope,
        transparently labeled as a snapshot from one run of
        `build/bin/benchmark_c_raw --json` (build-output, not checked
        in). Refresh by rebuilding the harness and updating the dict.

    Hybrid latency = Ed25519 + ML-DSA-65 (serial). The "ctypes overhead
    %" panel is computed directly from the two throughput series.
    """
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))

    implementations = [
        "AMA Cryptography\n(Raw C)",
        "AMA Cryptography\n(Python ctypes)",
    ]
    x_pos = np.arange(len(implementations))

    # ctypes per-op medians (us) — loaded from the checked-in JSON
    phase0 = _load_phase0_medians()
    ctypes_sign_us = phase0["Ed25519 sign (240B)"] + phase0["ML-DSA-65 sign"]
    ctypes_verify_us = phase0["Ed25519 verify (240B)"] + phase0["ML-DSA-65 verify"]
    # raw C per-op medians (us) — snapshot in RAW_C_MEDIANS_US
    raw_sign_us = RAW_C_MEDIANS_US["ed25519_sign"] + RAW_C_MEDIANS_US["mldsa65_sign"]
    raw_verify_us = RAW_C_MEDIANS_US["ed25519_verify"] + RAW_C_MEDIANS_US["mldsa65_verify"]

    # Derive overhead directly from the microsecond medians — rounding
    # throughputs to integers first (see ops/sec plots) can skew the
    # percentage and, for close values, even flip its sign. We only
    # round at display time.
    sign_overhead = (ctypes_sign_us / raw_sign_us - 1) * 100
    verify_overhead = (ctypes_verify_us / raw_verify_us - 1) * 100

    sign_throughput = [round(1_000_000 / raw_sign_us), round(1_000_000 / ctypes_sign_us)]
    verify_throughput = [round(1_000_000 / raw_verify_us), round(1_000_000 / ctypes_verify_us)]

    # Derived latency data (ms = 1000 / ops_per_sec)
    sign_latency = [1000 / v for v in sign_throughput]
    verify_latency = [1000 / v for v in verify_throughput]

    # === Panel 1: Throughput Line Chart ===
    ax1 = axes[0]
    ax1.plot(
        x_pos,
        sign_throughput,
        "o-",
        color="#3B82F6",
        linewidth=2.5,
        markersize=10,
        label="Hybrid Sign",
        markeredgecolor="white",
        markeredgewidth=2,
    )
    ax1.plot(
        x_pos,
        verify_throughput,
        "s-",
        color="#22C55E",
        linewidth=2.5,
        markersize=10,
        label="Hybrid Verify",
        markeredgecolor="white",
        markeredgewidth=2,
    )

    # Add value annotations
    for i, (s, v) in enumerate(zip(sign_throughput, verify_throughput)):
        ax1.annotate(
            f"{s:,}",
            (i, s),
            textcoords="offset points",
            xytext=(0, 12),
            ha="center",
            fontsize=9,
            fontweight="bold",
            color="#3B82F6",
        )
        ax1.annotate(
            f"{v:,}",
            (i, v),
            textcoords="offset points",
            xytext=(0, -18),
            ha="center",
            fontsize=9,
            fontweight="bold",
            color="#22C55E",
        )

    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(implementations, fontsize=9)
    ax1.set_ylabel("Operations per Second", fontsize=11)
    ax1.set_title("Throughput\n(Higher is Better)", fontsize=12, fontweight="bold")
    ax1.legend(loc="upper right", fontsize=9)
    ax1.set_ylim(0, max(sign_throughput + verify_throughput) * 1.3)
    ax1.grid(True, alpha=0.3)

    # === Panel 2: Latency Line Chart ===
    ax2 = axes[1]
    ax2.plot(
        x_pos,
        sign_latency,
        "o-",
        color="#3B82F6",
        linewidth=2.5,
        markersize=10,
        label="Sign Latency",
        markeredgecolor="white",
        markeredgewidth=2,
    )
    ax2.plot(
        x_pos,
        verify_latency,
        "s-",
        color="#22C55E",
        linewidth=2.5,
        markersize=10,
        label="Verify Latency",
        markeredgecolor="white",
        markeredgewidth=2,
    )

    for i, (s, v) in enumerate(zip(sign_latency, verify_latency)):
        ax2.annotate(
            f"{s:.3f}ms",
            (i, s),
            textcoords="offset points",
            xytext=(0, 12),
            ha="center",
            fontsize=9,
            fontweight="bold",
            color="#3B82F6",
        )
        ax2.annotate(
            f"{v:.3f}ms",
            (i, v),
            textcoords="offset points",
            xytext=(0, -18),
            ha="center",
            fontsize=9,
            fontweight="bold",
            color="#22C55E",
        )

    ax2.set_xticks(x_pos)
    ax2.set_xticklabels(implementations, fontsize=9)
    ax2.set_ylabel("Latency (milliseconds)", fontsize=11)
    ax2.set_title("Latency\n(Lower is Better)", fontsize=12, fontweight="bold")
    ax2.legend(loc="upper left", fontsize=9)
    ax2.set_ylim(0, max(sign_latency + verify_latency) * 1.25)
    ax2.grid(True, alpha=0.3)

    # === Panel 3: ctypes overhead relative to Raw C ===
    ax3 = axes[2]
    op_labels = ["Hybrid Sign", "Hybrid Verify"]
    overhead = [sign_overhead, verify_overhead]
    colors3 = ["#3B82F6", "#22C55E"]
    bars3 = ax3.bar(
        op_labels,
        overhead,
        color=colors3,
        edgecolor="white",
        linewidth=1.5,
        width=0.5,
    )
    # Axis range and label placement handle both positive (ctypes slower,
    # expected case) and hypothetical non-positive (ctypes as fast or
    # faster than raw C) values. `{:+.0f}%` always shows the sign so a
    # regression into negative territory is obvious.
    lo, hi = min([*overhead, 0.0]), max([*overhead, 0.0])
    span = max(hi - lo, 1.0)  # avoid zero-height axis if every bar is 0
    pad = span * 0.15
    for bar, val in zip(bars3, overhead):
        offset = span * 0.02
        ax3.text(
            bar.get_x() + bar.get_width() / 2,
            val + (offset if val >= 0 else -offset),
            f"{val:+.0f}%",
            ha="center",
            va="bottom" if val >= 0 else "top",
            fontsize=10,
            fontweight="bold",
            color="#1F2937",
        )
    ax3.set_ylabel("ctypes Overhead (%)", fontsize=11)
    ax3.set_title(
        "Python ctypes Overhead\n(Raw C = 0% baseline)",
        fontsize=12,
        fontweight="bold",
    )
    ax3.axhline(0, color="#9CA3AF", linewidth=0.8)
    ax3.set_ylim(lo - pad, hi + pad)
    ax3.grid(True, alpha=0.3, axis="y")

    # Overall title and footer
    fig.suptitle(
        "Hybrid Signature Performance: Raw C vs Python ctypes " "(Ed25519 + ML-DSA-65)",
        fontsize=14,
        fontweight="bold",
        y=1.02,
    )
    fig.text(
        0.5,
        -0.04,
        "ctypes data: loaded at chart-generation time from "
        "benchmarks/phase0_baseline_results.json. "
        "Raw C data: snapshot in RAW_C_MEDIANS_US (transcribed from "
        "build/bin/benchmark_c_raw --json on Linux x86_64 + AVX2; "
        "binary not checked in). "
        "Hybrid latency = Ed25519 + ML-DSA-65 (serial). "
        "Regenerate: `python tools/generate_visuals.py`.",
        ha="center",
        fontsize=9,
        color="#6B7280",
    )

    plt.tight_layout()
    plt.savefig(
        ASSETS_DIR / "performance_comparison.png",
        dpi=150,
        bbox_inches="tight",
        facecolor="white",
        edgecolor="none",
    )
    plt.close()
    print(f"Created: {ASSETS_DIR / 'performance_comparison.png'}")


def create_full_package_performance():
    """Create comprehensive full package performance visualization with layer breakdown."""
    fig, (ax_layers, ax_total) = plt.subplots(
        1, 2, figsize=(18, 8), gridspec_kw={"width_ratios": [2.2, 1]}
    )

    # Overall figure title
    fig.suptitle(
        "Full 4-Layer Package Performance Breakdown", fontsize=16, fontweight="bold", y=0.96
    )
    fig.text(
        0.5,
        0.91,
        "Component latencies and end-to-end throughput for the complete AMA Cryptography package",
        ha="center",
        fontsize=11,
        color="#6B7280",
    )

    # === LEFT PANEL: Per-layer latency breakdown ===
    # Per-layer ctypes-path medians (ms), loaded from the checked-in
    # phase0 JSON snapshot. Each bar is the median latency of one
    # standalone call to that primitive — not its share of a single
    # package_create call (the pipeline does not invoke every layer
    # exactly once, so layer sum ≠ package latency).
    phase0 = _load_phase0_medians()
    components = [
        ("ML-DSA-65 Signature", phase0["ML-DSA-65 sign"] / 1000, "#3B82F6"),
        ("Ed25519 Signature", phase0["Ed25519 sign (240B)"] / 1000, "#0EA5E9"),
        ("HKDF Key Derivation", phase0["HKDF-SHA3-256 (96B output)"] / 1000, "#8B5CF6"),
        ("HMAC-SHA3-256 Auth", phase0["HMAC-SHA3-256 (1KB)"] / 1000, "#22C55E"),
        ("SHA3-256 (1 KB)", phase0["SHA3-256 (1KB)"] / 1000, "#10B981"),
    ]

    names = [c[0] for c in components]
    times = [c[1] for c in components]
    colors_layers = [c[2] for c in components]
    layer_total = sum(times)

    y_pos = range(len(names))
    ax_layers.barh(y_pos, times, color=colors_layers, edgecolor="white", linewidth=1.5, height=0.55)

    ax_layers.set_yticks(y_pos)
    ax_layers.set_yticklabels(names, fontsize=10)
    ax_layers.set_xlabel("Median latency per standalone call (ms)", fontsize=10, labelpad=10)
    ax_layers.set_title(
        "Where the Time Goes (Per Layer, ctypes path)",
        fontsize=12,
        fontweight="bold",
        pad=15,
    )
    ax_layers.set_xlim(0, max(times) * 1.4)
    ax_layers.invert_yaxis()

    for i, (_name, t, _color) in enumerate(components):
        pct = 100 * t / layer_total
        label = f"{pct:.1f}%  |  {t:.3f} ms"
        ax_layers.text(
            t + max(times) * 0.01,
            i,
            label,
            va="center",
            fontsize=9,
            color="#374151",
            fontweight="bold",
        )

    # RFC 3161 annotation (optional, external)
    ax_layers.text(
        0.98,
        0.05,
        "RFC 3161 Timestamp: optional, external TSA latency\nnot included in any of these bars",
        transform=ax_layers.transAxes,
        ha="right",
        va="bottom",
        fontsize=8,
        color="#6B7280",
        style="italic",
        bbox=dict(
            boxstyle="round,pad=0.3", facecolor="#F9FAFB", edgecolor="#E5E7EB", linestyle="--"
        ),
    )

    # === RIGHT PANEL: End-to-end throughput (also from phase0) ===
    operations = ["Package\nCreate", "Package\nVerify"]
    pkg_create_us = phase0["Package create"]
    pkg_verify_us = phase0["Package verify"]
    throughput = [round(1_000_000 / pkg_create_us), round(1_000_000 / pkg_verify_us)]
    latency_ms = [pkg_create_us / 1000, pkg_verify_us / 1000]
    colors_total = ["#3B82F6", "#22C55E"]

    bars_total = ax_total.bar(
        operations, throughput, color=colors_total, edgecolor="white", linewidth=2, width=0.5
    )

    ax_total.set_ylabel("Operations per Second", fontsize=10)
    ax_total.set_title(
        "End-to-End Throughput\n(All 4 Layers Enabled)", fontsize=12, fontweight="bold", pad=15
    )
    ax_total.set_ylim(0, max(throughput) * 1.5)

    # Add value labels
    for bar, ops, ms in zip(bars_total, throughput, latency_ms):
        ax_total.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + max(throughput) * 0.04,
            f"{ops:,}\nops/sec\n({ms:.3f} ms)",
            ha="center",
            va="bottom",
            fontsize=11,
            fontweight="bold",
            color="#1F2937",
        )

    # Layer summary box
    ax_total.text(
        0.5,
        0.35,
        "4-layer pipeline:\n"
        "1. SHA3-256 Hash\n"
        "2. HMAC-SHA3-256\n"
        "3. Ed25519 + ML-DSA-65\n"
        "   (dual signature)\n"
        "4. HKDF Key Derivation\n"
        "+ RFC 3161 (optional)",
        transform=ax_total.transAxes,
        ha="center",
        va="top",
        fontsize=9,
        bbox=dict(boxstyle="round,pad=0.4", facecolor="#F3F4F6", edgecolor="#D1D5DB"),
    )

    # Bottom caption — be precise about the data source.
    fig.text(
        0.5,
        0.03,
        "All bars and the package_create / package_verify totals are "
        "loaded at chart-generation time from "
        "benchmarks/phase0_baseline_results.json (ctypes path; median_us). "
        "Reproduce: `python benchmarks/phase0_baseline.py`.",
        ha="center",
        fontsize=9,
        color="#6B7280",
        style="italic",
    )

    plt.tight_layout(rect=[0, 0.08, 1, 0.88])
    plt.savefig(
        ASSETS_DIR / "package_performance.png",
        dpi=150,
        bbox_inches="tight",
        facecolor="white",
        edgecolor="none",
    )
    plt.close()
    print(f"Created: {ASSETS_DIR / 'package_performance.png'}")


def create_monitoring_overhead():
    """Create compact monitoring overhead pie chart."""
    fig, ax = plt.subplots(figsize=(5, 4))

    sizes = [98, 2]
    labels = ["Crypto Ops\n(98%)", "3R Monitor\n(2%)"]
    colors = ["#3B82F6", "#F59E0B"]
    explode = (0, 0.05)

    ax.pie(
        sizes,
        explode=explode,
        labels=labels,
        colors=colors,
        autopct="",
        startangle=90,
        wedgeprops=dict(edgecolor="white", linewidth=2),
        textprops={"fontsize": 9},
    )

    ax.set_title("3R Monitoring Overhead", fontsize=11, fontweight="bold", pad=10)

    # Compact annotation
    fig.text(
        0.5,
        0.02,
        "<2% overhead for comprehensive security monitoring",
        ha="center",
        fontsize=8,
        style="italic",
        color="#6B7280",
    )

    plt.tight_layout(pad=0.5)
    plt.savefig(
        ASSETS_DIR / "monitoring_overhead.png",
        dpi=150,
        bbox_inches="tight",
        facecolor="white",
        edgecolor="none",
    )
    plt.close()
    print(f"Created: {ASSETS_DIR / 'monitoring_overhead.png'}")


def create_test_coverage():
    """Create enhanced test coverage visualization with percentages and cumulative data."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5), gridspec_kw={"width_ratios": [2, 1]})

    # Categories and counts are computed live from the working tree.
    # `_count_test_functions_by_category()` walks tests/test_*.py and
    # buckets each file into one of `_TEST_CATEGORY_RULES` (defined at
    # module scope) by filename predicate; `def test_` matches per file
    # are counted via regex. conftest.py is excluded (its `def test_`
    # entries are pytest fixtures, not tests).
    categories = [label for label, _ in _TEST_CATEGORY_RULES]
    test_counts, total_tests, unbucketed = _count_test_functions_by_category()
    # File count is derived once here and reused in both the suptitle
    # and the footer so they cannot disagree if tests are added or
    # removed. It matches the set walked by `_count_test_functions_by_category()`.
    n_files = len(list(TESTS_DIR.glob("test_*.py")))
    if unbucketed:
        # Surface in the build log so a new test file added without a
        # matching rule is noticed instead of silently dropped.
        print("WARN: test files without a category rule (will be excluded " "from chart):")
        for name, n in unbucketed:
            print(f"  - {name} ({n} tests)")
    percentages = (
        [100 * c / total_tests for c in test_counts] if total_tests else [0] * len(categories)
    )
    colors = ["#22C55E", "#3B82F6", "#8B5CF6", "#F59E0B", "#EF4444"]

    # === Left Panel: Horizontal bar chart with percentages ===
    bars = ax1.barh(categories, test_counts, color=colors, edgecolor="white", linewidth=2)

    ax1.set_xlabel("Number of Tests", fontsize=11)
    ax1.set_title("Test Distribution by Category", fontsize=12, fontweight="bold")
    ax1.set_xlim(0, max(test_counts) * 1.25)

    # Add count and percentage labels
    for bar, val, pct in zip(bars, test_counts, percentages):
        ax1.text(
            bar.get_width() + 3,
            bar.get_y() + bar.get_height() / 2,
            f"{val} ({pct:.1f}%)",
            ha="left",
            va="center",
            fontsize=10,
            fontweight="bold",
        )

    ax1.grid(True, alpha=0.3, axis="x")

    # === Right Panel: Cumulative coverage line chart ===
    cumulative = np.cumsum(test_counts)
    cumulative_pct = 100 * cumulative / total_tests
    y_pos = np.arange(len(categories))

    ax2.plot(
        cumulative_pct,
        y_pos,
        "o-",
        color="#3B82F6",
        linewidth=2.5,
        markersize=10,
        markeredgecolor="white",
        markeredgewidth=2,
    )
    ax2.fill_betweenx(y_pos, 0, cumulative_pct, alpha=0.2, color="#3B82F6")

    # Add percentage annotations
    for i, (cum, pct) in enumerate(zip(cumulative, cumulative_pct)):
        ax2.annotate(
            f"{pct:.0f}%\n({cum})",
            (pct, i),
            textcoords="offset points",
            xytext=(8, 0),
            ha="left",
            fontsize=9,
            fontweight="bold",
        )

    ax2.set_yticks(y_pos)
    ax2.set_yticklabels(categories, fontsize=9)
    ax2.set_xlabel("Cumulative Coverage (%)", fontsize=11)
    ax2.set_title("Cumulative Test Coverage", fontsize=12, fontweight="bold")
    ax2.set_xlim(0, 115)
    ax2.grid(True, alpha=0.3)

    # Overall title
    fig.suptitle(
        f"Test Suite Coverage: {total_tests} Tests Across {n_files} `test_*.py` Files",
        fontsize=14,
        fontweight="bold",
        y=1.02,
    )

    # Summary box
    fig.text(
        0.5,
        -0.06,
        f"v3.0.0 | Chart: {total_tests} test functions across "
        f"{n_files} test_*.py files "
        "(scanned live at chart-generation time by "
        "_count_test_functions_by_category(); excludes conftest.py). "
        "Independent reproduction: docs/METRICS_REPORT.md.",
        ha="center",
        fontsize=9,
        color="#6B7280",
        bbox=dict(boxstyle="round,pad=0.4", facecolor="#F3F4F6", edgecolor="#D1D5DB"),
    )

    plt.tight_layout()
    plt.savefig(
        ASSETS_DIR / "test_coverage.png",
        dpi=150,
        bbox_inches="tight",
        facecolor="white",
        edgecolor="none",
    )
    plt.close()
    print(f"Created: {ASSETS_DIR / 'test_coverage.png'}")


def create_ethical_binding_flow():
    """Create comprehensive ethical binding diagram showing 4 pillars with weights."""
    fig, ax = plt.subplots(figsize=(18, 12))
    ax.set_xlim(0, 18)
    ax.set_ylim(0, 12)
    ax.axis("off")

    # Title
    ax.text(
        9,
        11.5,
        "Ethical Vector Cryptographic Binding",
        ha="center",
        fontsize=20,
        fontweight="bold",
        color="#1F2937",
    )
    ax.text(
        9,
        10.9,
        "4 Omni-Code Ethical Pillars bound to keys and signatures via SHA3-256 + HKDF",
        ha="center",
        fontsize=12,
        color="#6B7280",
    )

    # Define the 4 pillars with their triads
    triads = [
        (
            "Omniscient: Wisdom",
            "#3B82F6",
            "Verification Layer",
            [
                ("verification", "Complete verification"),
                ("detection", "Multi-dimensional detection"),
                ("validation", "Data validation"),
            ],
        ),
        (
            "Omnipotent: Agency",
            "#22C55E",
            "Cryptographic Generation",
            [
                ("strength", "Maximum strength"),
                ("generation", "Key generation"),
                ("protection", "Real-time protection"),
            ],
        ),
        (
            "Omnidirectional: Geography",
            "#0EA5E9",
            "Defense-in-Depth",
            [
                ("defense", "Multi-layer defense"),
                ("temporal", "Temporal integrity"),
                ("coverage", "Attack surface coverage"),
            ],
        ),
        (
            "Omnibenevolent: Integrity",
            "#8B5CF6",
            "Ethical Constraints",
            [
                ("ethics", "Ethical foundation"),
                ("correctness", "Mathematical correctness"),
                ("hybrid", "Hybrid security"),
            ],
        ),
    ]

    # Draw 4 triad boxes in 2x2 grid on the left
    triad_positions = [(1.8, 8.2), (5.5, 8.2), (1.8, 4.8), (5.5, 4.8)]

    for idx, ((name, color, subtitle, pillars), (x, y)) in enumerate(zip(triads, triad_positions)):
        # Triad box
        rect = mpatches.FancyBboxPatch(
            (x - 1.6, y - 1.5),
            3.2,
            3.0,
            boxstyle="round,pad=0.02,rounding_size=0.15",
            facecolor=color,
            edgecolor="white",
            linewidth=2,
            alpha=0.15,
        )
        ax.add_patch(rect)

        # Triad header
        header_rect = mpatches.FancyBboxPatch(
            (x - 1.5, y + 1.0),
            3.0,
            0.45,
            boxstyle="round,pad=0.01,rounding_size=0.1",
            facecolor=color,
            edgecolor="white",
            linewidth=1,
        )
        ax.add_patch(header_rect)
        ax.text(
            x,
            y + 1.22,
            name,
            ha="center",
            va="center",
            fontsize=10,
            fontweight="bold",
            color="white",
        )
        ax.text(x, y + 0.75, f"({subtitle})", ha="center", va="center", fontsize=8, color="#374151")

        # Pillars
        for i, (pillar_name, pillar_desc) in enumerate(pillars):
            py = y + 0.3 - i * 0.55
            ax.text(
                x - 1.4,
                py,
                f"{pillar_name}",
                ha="left",
                va="center",
                fontsize=9,
                fontweight="bold",
                color="#1F2937",
            )
            ax.text(
                x + 1.5,
                py,
                "w=1.0",
                ha="right",
                va="center",
                fontsize=8,
                color=color,
                fontweight="bold",
            )
            ax.text(
                x - 1.4,
                py - 0.22,
                f"  {pillar_desc}",
                ha="left",
                va="center",
                fontsize=7,
                color="#6B7280",
            )

    # Aggregator box: Balanced Ethical Vector
    agg_x, agg_y = 9.2, 6.5
    agg_rect = mpatches.FancyBboxPatch(
        (agg_x - 1.3, agg_y - 0.8),
        2.6,
        1.6,
        boxstyle="round,pad=0.02,rounding_size=0.1",
        facecolor="#F3F4F6",
        edgecolor="#9CA3AF",
        linewidth=2,
    )
    ax.add_patch(agg_rect)
    ax.text(
        agg_x,
        agg_y + 0.35,
        "Balanced Vector",
        ha="center",
        va="center",
        fontsize=10,
        fontweight="bold",
        color="#1F2937",
    )
    ax.text(agg_x, agg_y - 0.05, "4 pillars", ha="center", va="center", fontsize=9, color="#374151")
    ax.text(
        agg_x,
        agg_y - 0.4,
        "each w = 1.0",
        ha="center",
        va="center",
        fontsize=9,
        color="#374151",
        fontweight="bold",
    )

    # Draw arrows from triads to aggregator
    # Arrow styling is set inline in annotate() calls below
    for x, y in triad_positions:
        ax.annotate(
            "",
            xy=(agg_x - 1.3, agg_y),
            xytext=(x + 1.6, y),
            arrowprops=dict(
                arrowstyle="->", color="#9CA3AF", lw=1.2, connectionstyle="arc3,rad=0.1"
            ),
        )

    # Cryptographic binding pipeline on the right
    pipeline_y = 6.5
    pipeline_boxes = [
        (11.5, "JSON Encode", "sorted keys", "#6366F1"),
        (13.5, "SHA3-256", "H(ethical_json)", "#3B82F6"),
        (15.5, "128-bit Sig", "H(E)[:16]", "#0EA5E9"),
    ]

    # Arrow from aggregator to pipeline
    ax.annotate(
        "",
        xy=(11.5 - 0.9, pipeline_y),
        xytext=(agg_x + 1.3, agg_y),
        arrowprops=dict(arrowstyle="->", color="#374151", lw=2),
    )

    for px, label, sublabel, color in pipeline_boxes:
        rect = mpatches.FancyBboxPatch(
            (px - 0.85, pipeline_y - 0.6),
            1.7,
            1.2,
            boxstyle="round,pad=0.02,rounding_size=0.1",
            facecolor=color,
            edgecolor="white",
            linewidth=2,
        )
        ax.add_patch(rect)
        ax.text(
            px,
            pipeline_y + 0.15,
            label,
            ha="center",
            va="center",
            fontsize=10,
            fontweight="bold",
            color="white",
        )
        ax.text(
            px,
            pipeline_y - 0.2,
            sublabel,
            ha="center",
            va="center",
            fontsize=8,
            color="white",
            alpha=0.9,
        )

    # Arrows between pipeline boxes
    for i in range(len(pipeline_boxes) - 1):
        x1 = pipeline_boxes[i][0] + 0.85
        x2 = pipeline_boxes[i + 1][0] - 0.85
        ax.annotate(
            "",
            xy=(x2, pipeline_y),
            xytext=(x1, pipeline_y),
            arrowprops=dict(arrowstyle="->", color="#374151", lw=2),
        )

    # Final output boxes
    output_y1, output_y2 = 8.5, 4.5

    # Arrow from 128-bit sig to outputs
    ax.annotate(
        "",
        xy=(16.2, output_y1 - 0.5),
        xytext=(15.5, pipeline_y + 0.6),
        arrowprops=dict(arrowstyle="->", color="#22C55E", lw=2),
    )
    ax.annotate(
        "",
        xy=(16.2, output_y2 + 0.5),
        xytext=(15.5, pipeline_y - 0.6),
        arrowprops=dict(arrowstyle="->", color="#22C55E", lw=2),
    )

    # HKDF Context output
    rect1 = mpatches.FancyBboxPatch(
        (15.3, output_y1 - 0.5),
        2.4,
        1.0,
        boxstyle="round,pad=0.02,rounding_size=0.1",
        facecolor="#22C55E",
        edgecolor="white",
        linewidth=2,
    )
    ax.add_patch(rect1)
    ax.text(
        16.5,
        output_y1 + 0.1,
        "HKDF Context",
        ha="center",
        va="center",
        fontsize=10,
        fontweight="bold",
        color="white",
    )
    ax.text(
        16.5,
        output_y1 - 0.2,
        "Key Derivation",
        ha="center",
        va="center",
        fontsize=8,
        color="white",
        alpha=0.9,
    )

    # Signature Message output
    rect2 = mpatches.FancyBboxPatch(
        (15.3, output_y2 - 0.5),
        2.4,
        1.0,
        boxstyle="round,pad=0.02,rounding_size=0.1",
        facecolor="#22C55E",
        edgecolor="white",
        linewidth=2,
    )
    ax.add_patch(rect2)
    ax.text(
        16.5,
        output_y2 + 0.1,
        "Signature Msg",
        ha="center",
        va="center",
        fontsize=10,
        fontweight="bold",
        color="white",
    )
    ax.text(
        16.5,
        output_y2 - 0.2,
        "Ed25519 + ML-DSA-65",
        ha="center",
        va="center",
        fontsize=8,
        color="white",
        alpha=0.9,
    )

    # Sum annotation
    ax.text(
        9.2,
        5.4,
        "Sum: 12 x 1.0 = 12.0",
        ha="center",
        va="center",
        fontsize=11,
        fontweight="bold",
        color="#059669",
        bbox=dict(boxstyle="round,pad=0.3", facecolor="#DCFCE7", edgecolor="#22C55E"),
    )

    # Caption
    ax.text(
        9,
        0.8,
        "The 4 Omni-Code Ethical Pillars form a balanced vector (each w = 3.0, total = 12.0).\n"
        "This vector is hashed with SHA3-256 and a 128-bit signature is injected into HKDF context and signature messages,\n"
        "cryptographically binding keys and signatures to an explicit ethical profile. This is binding, not enforcement.",
        ha="center",
        fontsize=10,
        style="italic",
        color="#6B7280",
    )

    plt.tight_layout()
    plt.savefig(
        ASSETS_DIR / "ethical_binding.png",
        dpi=150,
        bbox_inches="tight",
        facecolor="white",
        edgecolor="none",
    )
    plt.close()
    print(f"Created: {ASSETS_DIR / 'ethical_binding.png'}")


def create_quantum_comparison():
    """Create quantum vs classical security comparison."""
    fig, ax = plt.subplots(figsize=(10, 6))

    algorithms = [
        "RSA-2048\n(Classical)",
        "ECDSA-256\n(Classical)",
        "Ed25519\n(Classical)",
        "ML-DSA-65\n(Quantum-Resistant)",
    ]

    # Security levels (bits) - classical vs quantum
    classical_security = [112, 128, 128, 192]
    quantum_security = [0, 0, 0, 192]  # 0 means broken by quantum

    x = np.arange(len(algorithms))
    width = 0.35

    ax.bar(
        x - width / 2,
        classical_security,
        width,
        label="Classical Security",
        color="#3B82F6",
        edgecolor="white",
        linewidth=2,
    )
    ax.bar(
        x + width / 2,
        quantum_security,
        width,
        label="Quantum Security",
        color="#8B5CF6",
        edgecolor="white",
        linewidth=2,
    )

    ax.set_ylabel("Security Level (bits)", fontsize=12)
    ax.set_title("Classical vs Quantum Security Comparison", fontsize=14, fontweight="bold")
    ax.set_xticks(x)
    ax.set_xticklabels(algorithms)
    ax.legend(loc="upper left")
    ax.set_ylim(0, 250)

    # Add "BROKEN" labels for quantum-vulnerable algorithms
    for i, (c, q) in enumerate(zip(classical_security, quantum_security)):
        ax.text(
            i - width / 2, c + 5, f"{c}", ha="center", va="bottom", fontsize=10, fontweight="bold"
        )
        if q == 0:
            ax.text(
                i + width / 2,
                10,
                "BROKEN",
                ha="center",
                va="bottom",
                fontsize=9,
                fontweight="bold",
                color="#EF4444",
                rotation=90,
            )
        else:
            ax.text(
                i + width / 2,
                q + 5,
                f"{q}",
                ha="center",
                va="bottom",
                fontsize=10,
                fontweight="bold",
            )

    # Add annotation
    fig.text(
        0.5,
        -0.02,
        "ML-DSA-65 (Dilithium) provides 192-bit security against both classical and quantum attacks",
        ha="center",
        fontsize=10,
        style="italic",
        color="#6B7280",
    )

    plt.tight_layout()
    plt.savefig(
        ASSETS_DIR / "quantum_comparison.png",
        dpi=150,
        bbox_inches="tight",
        facecolor="white",
        edgecolor="none",
    )
    plt.close()
    print(f"Created: {ASSETS_DIR / 'quantum_comparison.png'}")


if __name__ == "__main__":
    print("Generating AMA Cryptography visual diagrams...")
    print("=" * 50)

    # defense_layers.png is owned by tools/generate_dashboards.py
    create_performance_comparison()
    create_full_package_performance()
    create_monitoring_overhead()
    create_test_coverage()
    create_ethical_binding_flow()
    create_quantum_comparison()

    print("=" * 50)
    print(f"All visuals saved to: {ASSETS_DIR}")
