#!/usr/bin/env python3
# Copyright (C) 2025-2026 Steel Security Advisors LLC
# SPDX-License-Identifier: Apache-2.0
"""
INVARIANT-8 at the point of release: the wheel we SHIP is the wheel a rebuild
produces.

Why this exists
---------------
``.github/workflows/static-analysis.yml``'s ``reproducible-build`` job proved
determinism honestly and completely — on a build that is thrown away.  It is
gated ``schedule || workflow_dispatch || pull_request``, and
``.github/workflows/release.yml`` never invoked it, so the artefacts that are
actually signed by sigstore, attested by SLSA and uploaded to PyPI were never
compared against anything.  The property was verified on one build and
claimed for a different one.

That is the whole gap.  Not "reproducibility is broken" — it holds, and the
PR-time job demonstrates it — but "the released bytes were never the bytes
under test".  A release is exactly when the claim has to be true, because it
is the only moment the artefact becomes something a third party will trust.

What it compares
----------------
Two directories of wheels: the ones ``build-wheels`` produced and uploaded,
and the ones an independent rebuild of the same commit produced.  For every
wheel present in both, every archive member is compared byte for byte, with
two documented exceptions:

``ama_cryptography/_integrity_signature.py`` — two literals of it
    INVARIANT-17 gives every build an EPHEMERAL signing keypair, so the
    artefact's ``INTEGRITY_PUBKEY_HEX`` and ``INTEGRITY_SIGNATURE_HEX`` are
    legitimately different between two builds of identical sources.  Those two
    literals, and nothing else, are masked; the rest of the file is compared
    byte for byte like any other member.  Each must be a single top-level
    assignment of a lowercase-hex string of its fixed width (64 and 128), so
    the mask cannot be stretched over anything else.  The file must also be
    PRESENT on both sides — an exempted file that vanished would be a silent
    hole, and its absence is itself a defect (the import-time integrity check
    degrades to digest-only without it).

    The whole file used to be exempt.  But every other field in it — the
    ``.py`` digest, the native-library digest, the binding-extension digest
    map — is a deterministic function of members this gate already requires to
    be byte-identical, and the file is the one that anchors every runtime
    integrity check.  A shipped artefact with its binding map emptied, or with
    an extra assignment appended, was compared against nothing while the gate
    reported the wheels byte-identical.

``*.dist-info/RECORD``
    Regenerated by the packaging tool and containing hashes of every other
    member, so its equality follows transitively from theirs.  It also pins a
    path the installer canonicalises.

Everything else — every ``.py``, the native ``libama_cryptography.so``, every
compiled Cython extension, the metadata — must match exactly.

Failure modes, all fail-closed
------------------------------
A comparison that could not be made is never reported as a comparison that
passed:

* a wheel in the shipped set with no counterpart in the rebuild;
* either directory containing no wheels at all;
* a wheel whose member NAMES differ (a file added or dropped between builds);
* ``_integrity_signature.py`` missing from either side, unparseable, or
  without exactly one well-formed assignment of each per-build literal.

Exit status
-----------
0  every shipped wheel matches its rebuild, member for member
1  a shipped wheel differs from its rebuild
2  the comparison could not be performed, or had nothing to compare
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import re
import sys
import zipfile
from pathlib import Path

#: Carries the two per-build literals; see the module docstring.  Matched
#: against the archive member path, which is always POSIX-separated inside a
#: wheel.
_EPHEMERAL_MEMBER = "ama_cryptography/_integrity_signature.py"

#: The literals INVARIANT-17 makes per-build, with their hex widths: the
#: ephemeral Ed25519 public key (32 bytes) and its signature (64 bytes).
_EPHEMERAL_FIELDS: dict[str, int] = {
    "INTEGRITY_PUBKEY_HEX": 64,
    "INTEGRITY_SIGNATURE_HEX": 128,
}

#: What a masked literal is replaced with before the byte comparison.
_MASK = b'"<per-build>"'

_LOWER_HEX_RE = re.compile(r"[0-9a-f]*")

#: Regenerated by the packaging tool; its equality follows from the rest.
_RECORD_SUFFIX = ".dist-info/RECORD"


def _is_excluded(member: str) -> bool:
    return member.endswith(_RECORD_SUFFIX)


def _masked_artefact(data: bytes) -> tuple[bytes | None, str | None]:
    """``data`` with its per-build literals masked, or why that is not possible.

    Each name in :data:`_EPHEMERAL_FIELDS` must be bound exactly once in the
    whole module, by a top-level ``NAME = "<hex>"`` whose value is lowercase
    hex of the recorded width.  Only that string literal's own bytes are
    replaced, located through ``ast``'s UTF-8 byte offsets, so the comparison
    that follows covers every other byte of the file — comments included.
    """
    try:
        tree = ast.parse(data.decode("utf-8"))
    except (UnicodeDecodeError, SyntaxError, ValueError) as exc:
        return None, f"does not parse as Python ({exc.__class__.__name__}: {exc})"
    bindings: dict[str, list[ast.Name]] = {name: [] for name in _EPHEMERAL_FIELDS}
    for node in ast.walk(tree):
        if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
            if node.id in bindings:
                bindings[node.id].append(node)
    offsets = [0]
    for line in data.split(b"\n"):
        offsets.append(offsets[-1] + len(line) + 1)
    spans: list[tuple[int, int]] = []
    for name, width in _EPHEMERAL_FIELDS.items():
        if len(bindings[name]) != 1:
            return None, f"binds {name} {len(bindings[name])} times; exactly one is required"
        statement = next(
            (
                stmt
                for stmt in tree.body
                if isinstance(stmt, ast.Assign)
                and len(stmt.targets) == 1
                and stmt.targets[0] is bindings[name][0]
            ),
            None,
        )
        value = statement.value if statement is not None else None
        if (
            not isinstance(value, ast.Constant)
            or not isinstance(value.value, str)
            or value.end_lineno is None
            or value.end_col_offset is None
        ):
            return None, f"{name} is not a top-level assignment of a string literal"
        if len(value.value) != width or not _LOWER_HEX_RE.fullmatch(value.value):
            return None, f"{name} is not {width} lowercase hex characters"
        start = offsets[value.lineno - 1] + value.col_offset
        end = offsets[value.end_lineno - 1] + value.end_col_offset
        spans.append((start, end))
    masked = data
    for start, end in sorted(spans, reverse=True):
        masked = masked[:start] + _MASK + masked[end:]
    return masked, None


def _compare_artefact(wheel: str, shipped: bytes, rebuilt: bytes) -> list[str]:
    """How the two integrity artefacts differ outside their per-build literals."""
    problems: list[str] = []
    masked: list[bytes] = []
    for label, data in (("shipped wheel", shipped), ("rebuild", rebuilt)):
        result, why = _masked_artefact(data)
        if result is None:
            problems.append(f"{wheel}: {_EPHEMERAL_MEMBER} in the {label} {why}.")
        else:
            masked.append(result)
    if problems:
        return problems
    lines_a = masked[0].split(b"\n")
    lines_b = masked[1].split(b"\n")
    if lines_a != lines_b:
        first = next(
            (i for i, (x, y) in enumerate(zip(lines_a, lines_b)) if x != y),
            min(len(lines_a), len(lines_b)),
        )
        problems.append(
            f"{wheel}: {_EPHEMERAL_MEMBER} differs outside "
            f"{' and '.join(_EPHEMERAL_FIELDS)}, first at line {first + 1} "
            f"({len(lines_a)} vs {len(lines_b)} lines). Only the per-build key and "
            f"signature may differ; every digest in this file is determined by "
            f"members that are byte-identical."
        )
    return problems


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def compare_wheel(shipped: Path, rebuilt: Path) -> list[str]:
    """Every way these two wheels differ, as human-readable problems."""
    problems: list[str] = []
    with zipfile.ZipFile(shipped) as a, zipfile.ZipFile(rebuilt) as b:
        names_a = {i.filename for i in a.infolist() if not i.is_dir()}
        names_b = {i.filename for i in b.infolist() if not i.is_dir()}

        only_shipped = sorted(names_a - names_b)
        only_rebuilt = sorted(names_b - names_a)
        for name in only_shipped:
            problems.append(f"{shipped.name}: {name} is in the shipped wheel but not the rebuild")
        for name in only_rebuilt:
            problems.append(f"{shipped.name}: {name} is in the rebuild but not the shipped wheel")

        # The one masked file must be present on both sides; an absent file
        # cannot be "legitimately different".
        for label, names in (("shipped wheel", names_a), ("rebuild", names_b)):
            if _EPHEMERAL_MEMBER not in names:
                problems.append(
                    f"{shipped.name}: {_EPHEMERAL_MEMBER} is missing from the {label}. "
                    f"Two of its literals are masked from the byte comparison because "
                    f"INVARIANT-17 makes them per-build; masking a file that is not there "
                    f"would be a hole, and a wheel without it verifies only digest-deep "
                    f"at import."
                )

        for name in sorted(names_a & names_b):
            if _is_excluded(name):
                continue
            data_a = a.read(name)
            data_b = b.read(name)
            if name == _EPHEMERAL_MEMBER:
                problems.extend(_compare_artefact(shipped.name, data_a, data_b))
                continue
            if data_a != data_b:
                problems.append(
                    f"{shipped.name}: {name} differs — shipped {_digest(data_a)[:16]}, "
                    f"rebuilt {_digest(data_b)[:16]} "
                    f"({len(data_a)} vs {len(data_b)} bytes)"
                )
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--shipped", required=True, type=Path, help="directory of shipped wheels")
    parser.add_argument("--rebuilt", required=True, type=Path, help="directory of rebuilt wheels")
    args = parser.parse_args(argv)

    for label, directory in (("--shipped", args.shipped), ("--rebuilt", args.rebuilt)):
        if not directory.is_dir():
            print(f"FATAL: {label} {directory} is not a directory.", file=sys.stderr)
            return 2

    shipped = sorted(args.shipped.glob("*.whl"))
    rebuilt = {p.name: p for p in args.rebuilt.glob("*.whl")}

    if not shipped:
        print(
            f"FATAL: no wheels in {args.shipped}. A release that verified nothing "
            f"must not report that the shipped artefacts are reproducible.",
            file=sys.stderr,
        )
        return 2
    if not rebuilt:
        print(f"FATAL: no wheels in {args.rebuilt} to compare against.", file=sys.stderr)
        return 2

    problems: list[str] = []
    compared = 0
    for wheel in shipped:
        counterpart = rebuilt.get(wheel.name)
        if counterpart is None:
            problems.append(
                f"{wheel.name}: the rebuild produced no wheel of this name "
                f"(rebuilt: {', '.join(sorted(rebuilt)) or 'none'}). A shipped wheel "
                f"the rebuild cannot reproduce is the case this gate exists for."
            )
            continue
        problems.extend(compare_wheel(wheel, counterpart))
        compared += 1

    for wheel in shipped:
        mark = "?" if wheel.name not in rebuilt else " "
        print(f"  {mark} {wheel.name}")

    if problems:
        print(
            f"\nRELEASE REPRODUCIBILITY CHECK FAILED — {len(problems)} difference(s) "
            f"between the shipped wheels and an independent rebuild of the same commit:",
            file=sys.stderr,
        )
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        print(
            "\nThe artefacts about to be signed and published are not the artefacts "
            "this source produces. Do not release until the difference is explained.",
            file=sys.stderr,
        )
        return 1

    if compared == 0:
        print("FATAL: no wheel was actually compared.", file=sys.stderr)
        return 2

    print(
        f"\nOK: {compared} shipped wheel(s) are byte-identical to an independent "
        f"rebuild, excluding only RECORD and the integrity artefact's per-build "
        f"public key and signature."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
