#!/usr/bin/env python3
# Copyright (C) 2025-2026 Steel Security Advisors LLC
# SPDX-License-Identifier: Apache-2.0
"""
INVARIANT-8 at the point of release: the wheel we SHIP is the wheel a rebuild
produces.

Why this exists
---------------
``.github/workflows/static-analysis.yml``'s ``reproducible-build`` job proved
determinism honestly and completely — on a build that is thrown away.  It is
gated ``schedule || workflow_dispatch || pull_request``, and
``.github/workflows/release.yml`` never invoked it, so the artefacts that are
actually signed by sigstore, attested by SLSA and uploaded to PyPI were never
compared against anything.  The property was verified on one build and
claimed for a different one.

That is the whole gap.  Not "reproducibility is broken" — it holds, and the
PR-time job demonstrates it — but "the released bytes were never the bytes
under test".  A release is exactly when the claim has to be true, because it
is the only moment the artefact becomes something a third party will trust.

What it compares
----------------
Two directories of wheels: the ones ``build-wheels`` produced and uploaded,
and the ones an independent rebuild of the same commit produced.  For every
wheel present in both, every archive member is compared byte for byte, with
two documented exceptions:

``ama_cryptography/_integrity_signature.py``
    INVARIANT-17 gives every build an EPHEMERAL signing keypair, so this file
    is legitimately different between two builds of identical sources.  It is
    excluded from the byte comparison and checked for PRESENCE instead — an
    excluded file that vanished would otherwise be a silent hole, and its
    absence is itself a defect (the import-time integrity check degrades to
    digest-only without it).

``*.dist-info/RECORD``
    Regenerated by the packaging tool and containing hashes of every other
    member, so its equality follows transitively from theirs.  It also pins a
    path the installer canonicalises.

Everything else — every ``.py``, the native ``libama_cryptography.so``, every
compiled Cython extension, the metadata — must match exactly.

Failure modes, all fail-closed
------------------------------
A comparison that could not be made is never reported as a comparison that
passed:

* a wheel in the shipped set with no counterpart in the rebuild;
* either directory containing no wheels at all;
* a wheel whose member NAMES differ (a file added or dropped between builds);
* ``_integrity_signature.py`` missing from either side.

Exit status
-----------
0  every shipped wheel matches its rebuild, member for member
1  a shipped wheel differs from its rebuild
2  the comparison could not be performed, or had nothing to compare
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import zipfile
from pathlib import Path

#: Legitimately build-specific; see the module docstring.  Matched against the
#: archive member path, which is always POSIX-separated inside a wheel.
_EPHEMERAL_MEMBER = "ama_cryptography/_integrity_signature.py"

#: Regenerated by the packaging tool; its equality follows from the rest.
_RECORD_SUFFIX = ".dist-info/RECORD"


def _is_excluded(member: str) -> bool:
    return member == _EPHEMERAL_MEMBER or member.endswith(_RECORD_SUFFIX)


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def compare_wheel(shipped: Path, rebuilt: Path) -> list[str]:
    """Every way these two wheels differ, as human-readable problems."""
    problems: list[str] = []
    with zipfile.ZipFile(shipped) as a, zipfile.ZipFile(rebuilt) as b:
        names_a = {i.filename for i in a.infolist() if not i.is_dir()}
        names_b = {i.filename for i in b.infolist() if not i.is_dir()}

        only_shipped = sorted(names_a - names_b)
        only_rebuilt = sorted(names_b - names_a)
        for name in only_shipped:
            problems.append(f"{shipped.name}: {name} is in the shipped wheel but not the rebuild")
        for name in only_rebuilt:
            problems.append(f"{shipped.name}: {name} is in the rebuild but not the shipped wheel")

        # The one exclusion that could hide something must be present on both
        # sides; an absent file cannot be "legitimately different".
        for label, names in (("shipped wheel", names_a), ("rebuild", names_b)):
            if _EPHEMERAL_MEMBER not in names:
                problems.append(
                    f"{shipped.name}: {_EPHEMERAL_MEMBER} is missing from the {label}. "
                    f"It is excluded from the byte comparison because INVARIANT-17 makes "
                    f"it per-build; excluding a file that is not there would be a hole, "
                    f"and a wheel without it verifies only digest-deep at import."
                )

        for name in sorted(names_a & names_b):
            if _is_excluded(name):
                continue
            data_a = a.read(name)
            data_b = b.read(name)
            if data_a != data_b:
                problems.append(
                    f"{shipped.name}: {name} differs — shipped {_digest(data_a)[:16]}, "
                    f"rebuilt {_digest(data_b)[:16]} "
                    f"({len(data_a)} vs {len(data_b)} bytes)"
                )
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--shipped", required=True, type=Path, help="directory of shipped wheels")
    parser.add_argument("--rebuilt", required=True, type=Path, help="directory of rebuilt wheels")
    args = parser.parse_args(argv)

    for label, directory in (("--shipped", args.shipped), ("--rebuilt", args.rebuilt)):
        if not directory.is_dir():
            print(f"FATAL: {label} {directory} is not a directory.", file=sys.stderr)
            return 2

    shipped = sorted(args.shipped.glob("*.whl"))
    rebuilt = {p.name: p for p in args.rebuilt.glob("*.whl")}

    if not shipped:
        print(
            f"FATAL: no wheels in {args.shipped}. A release that verified nothing "
            f"must not report that the shipped artefacts are reproducible.",
            file=sys.stderr,
        )
        return 2
    if not rebuilt:
        print(f"FATAL: no wheels in {args.rebuilt} to compare against.", file=sys.stderr)
        return 2

    problems: list[str] = []
    compared = 0
    for wheel in shipped:
        counterpart = rebuilt.get(wheel.name)
        if counterpart is None:
            problems.append(
                f"{wheel.name}: the rebuild produced no wheel of this name "
                f"(rebuilt: {', '.join(sorted(rebuilt)) or 'none'}). A shipped wheel "
                f"the rebuild cannot reproduce is the case this gate exists for."
            )
            continue
        problems.extend(compare_wheel(wheel, counterpart))
        compared += 1

    for wheel in shipped:
        mark = "?" if wheel.name not in rebuilt else " "
        print(f"  {mark} {wheel.name}")

    if problems:
        print(
            f"\nRELEASE REPRODUCIBILITY CHECK FAILED — {len(problems)} difference(s) "
            f"between the shipped wheels and an independent rebuild of the same commit:",
            file=sys.stderr,
        )
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        print(
            "\nThe artefacts about to be signed and published are not the artefacts "
            "this source produces. Do not release until the difference is explained.",
            file=sys.stderr,
        )
        return 1

    if compared == 0:
        print("FATAL: no wheel was actually compared.", file=sys.stderr)
        return 2

    print(
        f"\nOK: {compared} shipped wheel(s) are byte-identical to an independent "
        f"rebuild, excluding only the per-build integrity signature and RECORD."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
